- server/game/core/Game.js
- server/game/core/ability/CardAbilityStep.js
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/cost/GameActionCost.ts
- server/game/core/cost/GameSystemCost.ts
- server/game/core/cost/ICost.ts
- server/game/core/cost/MetaActionCost.ts
- server/game/core/gameSteps/phases/RegroupPhase.ts
- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/core/gameSystem/LastingEffectSystem.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/costs/CostLibrary.ts
- server/game/gameSystems/AttackSystem.ts
- server/game/gameSystems/ConditionalSystem.ts
- server/game/gameSystems/ExecuteHandlerSystem.ts
- server/game/gameSystems/ReplacementEffectSystem.ts
- server/game/gameSystems/SearchDeckSystem.ts
- server/game/gameSystems/SelectCardSystem.ts
- server/game/gameSystems/ViewCardSystem.ts
Realized that some of the "meta" game systems from the legacy L5R code override the event generation method to queue game steps which generate the events. Refactored the existing `generateEventsForAllTargets` method back to the way it was to be able to support that usage, but renamed it to `queueGenerateEventGameSteps` to make the purpose and usage clearer.
> Refactor `generateEventsForAllTargets` to `queueGenerateEventGameSteps`

- server/game/cards/01_SOR/VanguardInfantry.ts
- server/game/core/ability/TriggeredAbility.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/event/EventWindow.js
- server/game/core/event/ThenEventWindow.js
- server/game/core/gameSteps/abilityWindow/InitiateAbilityEventWindow.js
- server/game/core/gameSteps/abilityWindow/TriggeredAbilityWindow.ts
- server/game/core/utils/Contract.ts
- test/helpers/IntegrationHelper.js
- test/server/cards/01_SOR/VanguardInfantry.spec.js
We discovered a bug causing when-defeated triggers to completely fail. The reason was that triggers were being activated after events were resolved, so if a card left the arena during the event resolution window (e.g. due to defeat resolving) then its abilities would be unregistered and the defeat ability would never fire.
As a (possibly temporary) mitigation, we changed the resolution to work as follows:
1. Triggers are activated before event resolution, all triggered abilities are saved
2. Resolve event(s)
3. Activate triggers _again_ to catch any triggers such as when-played that would've been missed at step 1. Duplicate triggers are ignored.
4. Check if any triggering events were cancelled; if so, remove the relevant triggered abilities from the list to resolve
5. Resolve all …
> Fix "when defeated" trigger issues, add Vanguard Infantry

- .github/workflows/pullrequest.yml
- .github/workflows/update-cache.yml
- server/game/abilities/keyword/SaboteurDefeatShieldsAbility.ts
- server/game/cards/01_SOR/FallenLightsaber.ts
- server/game/cards/01_SOR/JedhaAgitator.ts
- server/game/cards/01_SOR/VadersLightsaber.ts
- server/game/cards/01_SOR/YodaOldMaster.ts
- server/game/cards/02_SHD/VambraceGrappleshot.ts
- server/game/core/Constants.ts
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/ability/TriggeredAbility.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/cardSelector/BaseCardSelector.js
- server/game/core/gameSteps/AbilityResolver.js
- server/game/core/gameSteps/abilityWindow/TriggeredAbilityWindow.ts
- server/game/core/gameSteps/prompts/HandlerMenuPrompt.js
- server/game/gameSystems/AttackStepsSystem.ts
- server/game/gameSystems/ConditionalSystem.ts
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/ExecuteHandlerSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/NoActionSystem.ts
- server/game/gameSystems/SelectCardSystem.ts
- test/helpers/IntegrationHelper.js
- test/server/cards/01_SOR/DeathTrooper.spec.js
- test/server/cards/01_SOR/FallenLightsaber.spec.js
- test/server/cards/01_SOR/JedhaAgitator.spec.js
- test/server/cards/01_SOR/VadersLightsaber.spec.js
Rounded out the ConditionalSystem so that it could be used to support most cases of the word "if" in card abilities (the primary exception being "if you do", which will require special logic).
Implemented a few cards to demonstrate how to implement the word "if" when used in:
- Normal triggered abilities
- Triggered abilities on attachments
- Constant abilities on attachments
Examples for other cases (particularly actions) will come in future PRs but the core functionality should be the same for all.
Also did some improvements to engine components to resolve issues found during testing, mainly in the TriggeredAbilityWindow. The fact that it would error out in a situation where there are multiple triggers on the same unit became a blocker, so for now we are just presenting every ability by …
> Add system for "if" conditions and some cards to test triggered and constant abilities

- server/game/cards/01_SOR/VadersLightsaber.ts
- server/game/gameSystems/SelectCardSystem.ts
- test/server/cards/01_SOR/VadersLightsaber.spec.js
Realized that we could get targeting to work correctly with a TargetResolver. Did a quick fix so that the "Pass" option will now appear correctly as expected (though we still need a fix for SelectCard at some point).
> Vader's lightsaber targeting hotfix

- .github/workflows/pullrequest.yml
- README.md
The parallel test setting was having issue in the past so we disabled it in github actions and recommended people not use it. It currently seems that the problem is gone, so re-enabling everything for now and will monitor to see if any issues occur.
> Re-enable parallel test run

- server/game/abilities/keyword/SaboteurDefeatShieldsAbility.ts
- server/game/core/attack/Attack.ts
- server/game/core/attack/AttackFlow.ts
- server/game/core/card/BaseCard.ts
- server/game/core/card/Card.ts
- server/game/core/card/EventCard.ts
- server/game/core/card/LeaderUnitCard.ts
- server/game/core/card/NonLeaderUnitCard.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/PrintedHp.ts
- server/game/core/card/propertyMixins/PrintedPower.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- test/server/actions/PlayUpgradeFromHand.spec.js
- test/server/cards/01_SOR/events/Disarm.spec.js
- test/server/cards/01_SOR/leaders/DirectorKrennicAspiringToAuthority.spec.js
- test/server/cards/01_SOR/units/JedhaAgitator.spec.js
- test/server/core/abilities/keyword/Grit.spec.js
- test/server/core/abilities/keyword/Raid.spec.js
Improved some of the common card properties to make them safer / easier to use:
- Added a `remainingHp` property that returns `max(0, hp - damage)`
- Renamed the `hp` and `power` properties to `getHp()` and `getPower()` to make it clearer that they involve some complex checking logic
- Added a guard on the `.upgrades` property so that it can't be used when the card is not in an arena (same as for damage)
- Added a similar guard on the `.activeAttack` property
As a result of the last change above, found an issue where units that were defeated in combat would still have an "active" attack after moving to discard. This does not currently cause any problems but is not in line with the rules as the unit is no longer involved in an attack once defeated. It could also cause confusion in the …
> Improve some card properties and fix ActiveAttack issue

- server/game/core/card/propertyMixins/UnitProperties.ts
With the change to the defeat system, checking for defeat at damage time is now redundant since the check will happen at the next call to resolveGameState.
> Remove unnecessary defeat check from damage method

- docs/implementing-cards.md
- server/game/cards/01_SOR/upgrades/FallenLightsaber.ts
- server/game/cards/01_SOR/upgrades/JediLightsaber.ts
- server/game/cards/01_SOR/upgrades/LukesLightsaber.ts
- server/game/cards/01_SOR/upgrades/VadersLightsaber.ts
- server/game/cards/02_SHD/upgrades/VambraceGrappleshot.ts
- server/game/core/card/UpgradeCard.ts
- test/helpers/DeckBuilder.js
- test/helpers/PlayerInteractionWrapper.js
- test/server/actions/PlayUpgradeFromHand.spec.js
- test/server/cards/01_SOR/leaders/GrandMoffTarkinOversectorGovernor.spec.js
- test/server/cards/01_SOR/tokens/Shield.spec.js
- test/server/cards/01_SOR/upgrades/FallenLightsaber.spec.js
- test/server/cards/01_SOR/upgrades/JediLightsaber.spec.js
- test/server/cards/02_SHD/upgrades/VambraceGrappleshot.spec.js
- test/server/core/card/Upgrade.spec.js
We had accumulated a lot of small TODOs related to implementing and testing upgrade cards. Handled them all in a batch. Specific improvements:
- There is now a dedicated method for setting up attachment conditions
- Made the `gainCondition` option for enabling / disabling gained effects on the attached card a property instead of a method parameter to improve readability
- Added support for declaring deployed leaders to have attached upgrades in test setup
- Updated some older tests to use the most up-to-date test helper methods
> Batch of improvements to upgrade setup + tests

- server/game/cards/01_SOR/upgrades/FallenLightsaber.ts
- server/game/core/Player.js
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/gameSystems/DefeatCardSystem.ts
- test/server/cards/01_SOR/units/GeneralVeersBlizzardForceCommander.spec.js
We had a potential issue with timing where if a unit was targeted with multiple simultaneous effects, the first of which was a damage effect that defeated the unit, the other effects would still successfully activate even though the unit is supposed to have technically entered a defeated state.
Not sure yet if there is a specific case where this impacts game behavior, but wanted to get the change in now to catch potential edge cases when they do come up.
> Better logic for defeat and simultaneous effects

- scripts/build-test.js
- server/game/abilities/keyword/AmbushAbility.ts
- server/game/actions/PlayUnitAction.ts
- server/game/cards/01_SOR/units/AdmiralPiettCaptainOfTheExecutor.ts
- server/game/cards/02_SHD/units/PrivateerScyk.ts
- server/game/core/Game.js
- server/game/core/attack/AttackFlow.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/event/EventWindow.js
- server/game/core/event/GameEvent.ts
- server/game/core/gameSteps/abilityWindow/InitiateAbilityEventWindow.js
- server/game/core/gameSteps/abilityWindow/TriggeredAbilityWindow.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/01_SOR/units/AdmiralPiettCaptainOfTheExecutor.spec.ts
- test/server/cards/01_SOR/units/DelMeekoProvidingOverwatch.spec.ts
- test/server/cards/01_SOR/units/TieAdvanced.spec.ts
- test/server/cards/02_SHD/events/FellTheDragon.spec.ts
- test/server/cards/02_SHD/units/PrivateerScyk.spec.ts
- test/server/core/ongoingEffects/CostAdjusters.spec.ts
We had a bug where "gain ambush" and "gain shielded" would not work because units register those abilities when they move into the arena, but the effects that give them abilities resolve after they get to the arena.
Made a few changes to address this. The first is refactoring the event window so that we emit events again after a `resolveGameState` call so that any abilities gained during the event window resolution can successfully trigger.
The other change is refactoring how we handle triggered abilities for keywords. We previously would register keywords at a time point before the event actually resolves (e.g., registering when-played abilities when the unit enters the arena). However, it is possible that gain or lose ability effects can happen in between those two time points, so we …
> Fix windows so that "gain ambush" and "gain shielded" work correctly

- server/game/IDamageOrDefeatSource.ts
- server/game/cards/01_SOR/units/AgentKallusSeekingTheRebels.ts
- server/game/cards/01_SOR/units/ColonelYularenIsbDirector.ts
- server/game/cards/02_SHD/units/SalaciousCrumbObnoxiousPet.ts
- server/game/core/Player.js
- server/game/core/card/Card.ts
- server/game/core/card/CardTypes.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/event/EventWindow.js
- server/game/core/gameSteps/prompts/SelectCardPrompt.js
- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/core/ongoingEffect/OngoingEffect.js
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/DefeatCardSystem.ts
- server/game/gameSystems/FrameworkDefeatCardSystem.ts
- server/game/stateWatchers/CardsEnteredPlayThisPhaseWatcher.ts
- server/game/stateWatchers/CardsLeftPlayThisPhaseWatcher.ts
- test/server/cards/01_SOR/units/AgentKallusSeekingTheRebels.spec.ts
- test/server/cards/01_SOR/units/ColonelYularenIsbDirector.spec.ts
- test/server/cards/01_SOR/units/MaceWinduPartyCrasher.spec.ts
- test/server/cards/02_SHD/units/SalaciousCrumbObnoxiousPet.spec.ts
- test/server/cards/02_SHD/units/SupremeLeaderSnokeShadowRuler.spec.ts
- test/server/core/card/UniqueRule.spec.ts
Implemented the rules for enforcing unique cards in play. Added tests for the edge cases of Yularen and Snoke to confirm that they work correctly.
Yularen worked out of the box. Snoke required adding some additional logic to disable ongoing effects when a card has a pending defeat. Also, refactored the "pending defeat" code to be clearer and operate more consistently.
> Add unique rules

- server/game/cards/01_SOR/units/ISBAgent.ts
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- test/server/cards/01_SOR/units/ISBAgent.spec.ts
Adds the implementation for ISB Agent and slightly changes the logic for the "Choose no target" button to avoid showing it alongside the "Done" button when only one card needs to be selected.
> Add ISB Agent implementation

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
Rearranged things in CardTargetResolver so that that the condition filter is checked before the system's hasLegalTarget is invoked. This is because the condition filter might be able to prevent the system from trying to properties are cards that are in an invalid state (e.g., attempting to read the damage off of a card in hand).
> Move card target condition check before system check

- server/game/core/Game.js
- server/game/core/Player.js
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/gameSteps/prompts/ResourcePrompt.ts
- server/gamenode/defaultGame.js
Adds additional piles to the gamestate. Also updates some properties on cardSummary so that they can be properly rendered and suppress mouseclick events when not selectable.
> Add card piles to gamestate

- server/game/core/gameSystem/AggregateSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/SequentialSystem.ts
- server/game/gameSystems/SimultaneousSystem.ts
We ran into a scenario where we needed to generate a list of systems from context for an aggregate system. Added support for doing that in both sequential and simultaneous. Tested in another branch.
> Add support for system array factories for aggregate systems

- server/game/core/ability/CardAbilityStep.js
`ifYouDoContext` had a bug because the `ifYouDo` was not being evaluated as a function. Fixed, tested in other branches
> Fix if you do context bug

- server/game/Interfaces.ts
- server/game/core/Constants.ts
- server/game/core/ability/AbilityContext.ts
- server/game/core/card/Card.ts
- server/game/core/gameSteps/SimultaneousEffectWindow.ts
- server/game/core/gameSteps/prompts/HandlerMenuPrompt.js
- server/game/core/gameSteps/prompts/SelectCardPrompt.js
- server/game/core/ongoingEffect/IConstantAbility.ts
- server/game/core/ongoingEffect/OngoingCardEffect.ts
- server/game/core/ongoingEffect/OngoingEffect.ts
- server/game/core/ongoingEffect/OngoingEffectBuilder.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/core/ongoingEffect/OngoingEffectSource.ts
- server/game/core/ongoingEffect/OngoingPlayerEffect.ts
- server/game/core/ongoingEffect/effectImpl/OngoingEffectImpl.ts
- server/game/core/ongoingEffect/effectImpl/StatsModifierWrapper.ts
- server/game/core/utils/Contract.ts
- server/game/gameSystems/PlayerLastingEffectSystem.ts
Started to dig into card vs player effects but turned into just converting the OnGoingEffects classes into TS, so I made a PR for the conversion alone.
NOTES:
- Some of the JS files didn't like importing OngoingEffectSource as a default export and I'm not sure why, so for now I've removed the default export.
- Moved targetController assignment logic to the base OngoingEffect class, as both derived classes did the exact same thing.
- Removed unused property.matchTarget assignment in OngoingCardEffect, it's assigning to the properties object, but the base class already does this logic and does it before this line.
- Still has some "any" types, OngoingEffect's "ability" field is seemingly assigned to two completely different types, as noted. A few things I set as "GameObject" because I was …
> Ongoing Effects TS Conversion

- server/game/actions/InitiateAttackAction.ts
- server/game/actions/PlayUpgradeAction.ts
- server/game/core/cost/GameSystemCost.ts
- server/game/gameSystems/InitiateAttackSystem.ts
There was an issue where specifying `ignoredRequirements: ['cost']` for an attack didn't work and was causing a bug for a card impl. Figured out a fix, tested and working in that branch.
> Bug fix for allowing exhausted attackers

- test/scenarios/ability/MultiplePlay.spec.ts
- test/server/cards/01_SOR/units/GeneralKrellHeartlessTactician.spec.ts
- test/server/core/abilities/keyword/Ambush.spec.ts
- test/server/core/abilities/keyword/Bounty.spec.ts
- test/server/core/abilities/keyword/Grit.spec.ts
- test/server/core/abilities/keyword/Overwhelm.spec.ts
- test/server/core/abilities/keyword/Raid.spec.ts
- test/server/core/abilities/keyword/Restore.spec.ts
- test/server/core/abilities/keyword/Saboteur.spec.ts
- test/server/core/abilities/keyword/Sentinel.spec.ts
- test/server/core/abilities/keyword/Shielded.spec.ts
- All keywords except Smuggle (under test/core/abilities/keyword)
- two when-played ability, one on-attack ability (ideally something simple like draw a card)
- One constant ability like Snoke or Dodonna Something like Reputable Hunter that gives itself a play discount effect
- a generic "when defeated" ability test where we defeat, recall with Emperor's Legion, play, then defeat again
- a test for General Krell, there's already a comment note there. basically we want to start him in play, defeat, recall to hand, play again, and then confirm that friendly units draw exactly 1 card when they die (the concern is that they might gain two instances of his ability)
> #Added Additional on-play tests

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/gameSteps/AbilityResolver.js
We found that in some cases, marking a triggered ability optional would case a prompt to be displayed for activating the ability even if there were no "effective" targets (e.g., an exhaust ability trying to activate when all units are exhausted). Added a shortcut for this, tested in a different branch.
> Add shortcut in ability resolver for no effective targets

- server/game/core/ongoingEffect/effectImpl/GainAbility.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
In another branch we hit an issue where a gained ability couldn't correctly generate a name for itself when created from an attack lasting effect due to the lack of a name on the effect (or on the originating ability). Added a way to declare when the ability is coming from a lasting effect. Tests pass in the feature branch.
>  Bug fix for gained ability from lasting effect

- server/game/cards/03_TWI/units/AnakinSkywalkerMaverickMentor.ts
- server/game/cards/03_TWI/units/CloneHeavyGunner.ts
- server/game/cards/03_TWI/units/CoruscantGuard.ts
- server/game/cards/03_TWI/units/RecklessTorrent.ts
- server/game/core/Constants.ts
- server/game/core/ability/AbilityTypes.ts
- server/game/core/ability/KeywordHelpers.ts
- server/game/core/ability/KeywordInstance.ts
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/ongoingEffect/effectImpl/GainAbility.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/helpers/IntegrationHelper.js
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/03_TWI/units/AnakinSkywalkerMaverickMentor.spec.ts
- test/server/cards/03_TWI/units/CloneHeavyGunner.spec.ts
- test/server/cards/03_TWI/units/CoruscantGuard.spec.ts
- test/server/cards/03_TWI/units/RecklessTorrent.spec.ts
- test/server/core/abilities/keyword/Coordinate.spec.ts
- test/server/core/abilities/keyword/Raid.spec.ts
- test/server/core/abilities/keyword/Restore.spec.ts
- test/server/core/abilities/keyword/Shielded.spec.ts
Added support for the Coordinate keyword, using similar mechanisms to the Bounty keyword. Added several test units to confirm that the timing works and that triggered and constant abilities work.
Two special cases are not covered in this PR and will require additional work:
- Coordinate on leaders (Ahsoka, Padme)
- "Gain coordinate" (For the Republic)
> Coordinate keyword

- server/game/core/Constants.ts
- server/game/gameSystems/GiveTokenUpgradeSystem.ts
Refactor GiveTokenUpgrade to create tokens and then generate separate attach events. This establishes a pattern for creating token units in the future.
> Refactor GiveTokenUpgradeSystem

- server/game/TargetInterfaces.ts
- server/game/cards/01_SOR/events/Restock.ts
- server/game/cards/03_TWI/events/BoldResistance.ts
- server/game/core/cardSelector/BaseCardSelector.js
- server/game/core/cardSelector/CardSelectorFactory.js
- server/game/core/utils/Helpers.ts
- test/server/cards/03_TWI/events/BoldResistance.spec.ts
Three things in here:
- Created a new multiSelectCardCondition property for handling groups of selected cards
- Implemented the Bold Resistance Card  (TWI # 153)
- Removed the sameDiscardPile property and adjusted Restock to use the new code
> New multiSelectCardCondition, TWI #153 Bold Resistance Card and sameDiscardPile cleanup

- server/game/core/card/EventCard.ts
The guard in the EventCard.ts constructor was fully blocking unimplemented event cards from being instantiated, which blocks testing. Fixed the check to only happen if there's an implementation file.
> Fix unimplemented event card bug

- .github/workflows/pullrequest.yml
- .github/workflows/update-cache.yml
- bin/fetchdata.js
- server/game/cards/02_SHD/events/ANewAdventure.ts
- server/game/cards/02_SHD/events/AlteringTheDeal.ts
- server/game/cards/02_SHD/leaders/CadBaneHeWhoNeedsNoIntroduction.ts
- server/game/cards/02_SHD/units/UnlicensedHeadhunter.ts
- server/game/core/ability/CardAbilityStep.js
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/ongoingEffect/OngoingEffect.ts
- test/helpers/IntegrationHelper.js
- test/helpers/PlayerInteractionWrapper.js
- test/helpers/Util.js
- test/server/cards/01_SOR/leaders/BobaFettCollectingTheBounty.spec.ts
- test/server/cards/01_SOR/units/GeneralKrellHeartlessTactician.spec.ts
- test/server/cards/02_SHD/events/ANewAdventure.spec.ts
- test/server/cards/02_SHD/events/AlteringTheDeal.spec.ts
- test/server/cards/02_SHD/leaders/CadBaneHeWhoNeedsNoIntroduction.spec.ts
- test/server/cards/02_SHD/units/UnlicensedHeadhunter.spec.ts
Added some open cards from SHD (images below). Also fixed a few bugs and improved some test stuff, the major ones are:
- A data format change in the SWU official site meant that we were incorrectly reading the aspects for double-aspect cards like A New Adventure. Fixed this and corrected some broken tests.
- Improved test failure reporting to show prompts for both players instead of just the active one to make it easier to figure out failure causes faster
> Add some cards from SHD

- test/helpers/IntegrationHelper.d.ts
- test/helpers/IntegrationHelper.js
- test/helpers/Util.js
- test/scenarios/constantEffectInteractions/LosingAndGainingKeywords.spec.ts
- test/server/actions/UnitAttack.spec.ts
- test/server/cards/01_SOR/events/OverwhelmingBarrage.spec.ts
- test/server/cards/01_SOR/events/TacticalAdvantage.spec.ts
- test/server/cards/01_SOR/events/Takedown.spec.ts
- test/server/cards/01_SOR/leaders/ChewbaccaWalkingCarpet.spec.ts
- test/server/cards/01_SOR/leaders/LeiaOrganaAllianceGeneral.spec.ts
- test/server/cards/01_SOR/leaders/SabineWrenGalvanizedRevolutionary.spec.ts
- test/server/cards/01_SOR/units/DeathTrooper.spec.ts
- test/server/cards/01_SOR/units/EmperorPalpatineMasterOfTheDarkSide.spec.ts
- test/server/cards/01_SOR/units/GladiatorStarDestroyer.spec.ts
- test/server/cards/01_SOR/units/SabineWrenExplosivesArtist.spec.ts
- test/server/cards/02_SHD/events/MidnightRepairs.spec.ts
- test/server/cards/02_SHD/units/OmegaPartOfTheSquad.spec.ts
- test/server/cards/02_SHD/units/ProtectorOfTheThrone.spec.ts
- test/server/cards/02_SHD/units/SupercommandoSquad.spec.ts
- test/server/core/Game.spec.ts
- test/server/core/card/Leader.spec.ts
- test/server/gameSystems/DrawSystem.spec.ts
A common hangup in testing, especially for new folks, is not realizing that a prompt is open and waiting for a click. To help people catch this, added a check at the end of every test case which will throw an error if either player has an open prompt (so long as they end in the action phase).
This functionality can be disabled by setting `context.allowOpenPromptAtEndOfTest = true`. Updated all affected existing test cases to either not end with an open prompt or to use the above setting to disable the check.
> Add check for open prompt at end of test cases

- server/game/gameSystems/DiscardCardsFromHandSystem.ts
The DiscardCardsFromHandSystem wasn't supplying a default value for the card type filter, which was breaking some attempts at card implementations. Fixed the bug here and validated working on another branch.
> Fix bug with discard from hand system

- test/helpers/IntegrationHelper.js
We had an issue where the open prompt check at the end of a test would trigger even if the test failed due to known reasons (exception or expectation failure). This creates confusion so I added a check to keep it from happening.
Unfortunately the mechanism for this doesn't work in parallel mode, so in that case I added an error message indicating that we need to run in serial for more details.
> Don't do open prompt check if test failed

- server/game/cards/03_TWI/units/MultitroopTransport.ts
- server/game/core/Constants.ts
- server/game/core/ability/KeywordHelpers.ts
- test/server/cards/03_TWI/units/MultitroopTransport.spec.ts
The engine was choking on cards with the Exploit keyword since it didn't have an entry for it to parse. Added the logic for that and tested by adding Multi-Troop Transport.
Exploit functionality is not present at all but the keyword can at least be parsed successfully and then ignored.
> Add Multi-Troop Transport and add Exploit parsing

- .gitignore
- server/game/cards/03_TWI/events/BreakingIn.ts
- server/game/gameSystems/AttackStepsSystem.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
- test/server/cards/03_TWI/events/BreakingIn.spec.ts
There was an issue preventing us from implementing cards that allow a unit to attack and gain Saboteur for that attack. Specifically, the "gain Saboteur" effect would not be applied until after targeting, meaning that it wouldn't have any impact on sentinel.
Hardcoded support for this into the AttackStepsSystem and implemented Breaking In to test it. Also did some general cleanup of the CardLastingEffectSystem and AttackStepsSystem.
> Add support for gaining Saboteur for attack duration

- server/game/cards/02_SHD/events/CalculatedLethality.ts
- server/game/cards/02_SHD/leaders/FinnThisIsARescue.ts
- server/game/cards/02_SHD/units/RoseTicoDedicatedToTheCause.ts
- server/game/core/event/GameEvent.ts
- server/game/core/gameSteps/prompts/DistributeAmongTargetsPrompt.ts
- server/game/gameSystems/DefeatCardSystem.ts
Per the SWU rules, if a defeated card is referred to later in the same ability then any properties referred to are as if it was still in the arena. We were using a workaround to handle this out but added a feature to handle it more elegantly.
> Add "last known information" to defeat system

- server/game/gameSystems/CreateTokenUnitSystem.ts
Targeting for token unit generation was broken, they would always be created for the triggering player. Confirmed this fix works in another branch.
> Fix token units bug

- server/game/Interfaces.ts
- server/game/cards/01_SOR/units/FrontlineShuttle.ts
- server/game/cards/01_SOR/units/SawGerreraExtremist.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/ability/PlayCardAction.ts
- server/game/core/ability/PlayerAction.js
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/cost/ICost.ts
- server/game/costs/CostLibrary.ts
- server/game/gameSystems/SelectCardSystem.ts
- test/helpers/IntegrationHelper.js
- test/scenarios/event/ReplacementEffect.spec.ts
- test/server/cards/02_SHD/events/Headhunting.spec.ts
- test/server/cards/02_SHD/units/FinalizerMightOfTheFirstOrder.spec.ts
- test/server/cards/02_SHD/units/KetsuOnyoOldFriend.spec.ts
- test/server/cards/02_SHD/upgrades/HeroicResolve.spec.ts
Discovered that SelectCardSystem was not respecting autoSingleTarget and assuming it was true always. Updated this behavior, which broke several tests. In some cases the tests just needed updating, in other cases the abilities themselves were implemented wrong. Cleaned up everything and it is now working.
> Update SelectCardSystem to respect autoSingleTarget, update tests

- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/gameSystems/DelayedEffectSystem.ts
We hit an issue with the Sneak Attack branch where a delayed effect weren't correctly having its `target` property set but the error was extremely unclear. In addition, the target resolution wasn't being handled correctly if `selectCard` is used. Added better error checking and a clearer message, and fixed the target resolution.
> Fix delayed effect targeting bug

- server/game/gameSystems/DiscardCardsFromHandSystem.ts
Bug fix where discard from hand system was generating a blank event when no card was discarded
> Bug fix for DiscardCardsFromHandSystem

- eslint.config.mjs
The advanced ESLint options related to imports (mostly tracking import cycles) are too slow to be left on all the time. Commented them out and we can re-run on a regular cadence to do cleanup.
> Disable project parsing options by default

- eslint.config.mjs
- server/game/Interfaces.ts
- server/game/abilities/keyword/ExploitPlayCardResourceCost.ts
- server/game/actions/PlayEventAction.ts
- server/game/actions/PlayUnitAction.ts
- server/game/actions/PlayUpgradeAction.ts
- server/game/cards/01_SOR/events/Bamboozle.ts
- server/game/cards/02_SHD/units/TechSourceOfInsight.ts
- server/game/core/Player.js
- server/game/core/ability/KeywordHelpers.ts
- server/game/core/ability/PlayCardAction.ts
- server/game/core/card/Card.ts
- server/game/core/card/CardTypes.ts
- server/game/core/card/EventCard.ts
- server/game/core/card/NonLeaderUnitCard.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Cost.ts
- server/game/core/cost/ICost.ts
- server/game/core/gameSteps/ActionWindow.js
- server/game/core/ongoingEffect/effectImpl/StaticOngoingEffectImpl.ts
- server/game/core/utils/Helpers.ts
- server/game/costs/CostLibrary.ts
- server/game/costs/PlayCardResourceCost.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
- server/game/gameSystems/PlayCardSystem.ts
- test/server/cards/01_SOR/events/Bamboozle.spec.ts
- test/server/cards/02_SHD/units/TechSourceOfInsight.spec.ts
Added Tech unit, which required refactoring the methods for generating smuggle actions since they were hardcoded to assume only one smuggle keyword existed. Now it will automatically determine the best
> Implement Tech unit

- server/game/core/Player.js
- server/game/core/card/Card.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- Removed the `hideWhenFaceup` element (remnant from jigoku engine)
- Return facedown cards with no details based off active player and zone (e.g. only show opposing cards when they are in play)
> fix: hide opposing players cards in the gamestate

- server/game/cards/01_SOR/leaders/ChirrutImweOneWithTheForce.ts
- server/game/cards/01_SOR/units/RelentlessKonstantinesFolly.ts
- server/game/cards/02_SHD/units/FirstLightHeadquartersOfTheCrimsonDawn.ts
- server/game/cards/02_SHD/units/MillenniumFalconLandosPride.ts
- server/game/core/Constants.ts
- server/game/core/ability/KeywordInstance.ts
- server/game/core/ability/PlayCardAction.ts
- server/game/core/card/LeaderCard.ts
- server/game/core/card/LeaderUnitCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/StandardAbilitySetup.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/01_SOR/events/Bamboozle.spec.ts
- test/server/cards/01_SOR/leaders/ChirrutImweOneWithTheForce.spec.ts
- test/server/cards/02_SHD/units/FirstLightHeadquartersOfTheCrimsonDawn.spec.ts
- test/server/cards/02_SHD/units/MillenniumFalconLandosPride.spec.ts
- test/server/cards/02_SHD/units/TechSourceOfInsight.spec.ts
Implemented Chirrut, First Light, Falcon2. Also some random other improvements.
> Chirrut, First Light, Falcon2

- server/game/cards/03_TWI/units/SlyMooreSecretiveAdvisor.ts
- test/server/cards/03_TWI/units/SlyMooreSecretiveAdvisor.spec.ts
> Implementing Sly Moore Secretive Advisor

- server/game/Interfaces.ts
- server/game/cards/03_TWI/units/AaylaSecuraMasterOfTheBlade.ts
- test/server/cards/03_TWI/units/AaylaSecuraMasterOfTheBlade.spec.ts
-----
I had hoped to land on a solution that would work for other similar damage prevention abilities (like [Boba Fett's Armor](https://swudb.com/card/shd/224/boba-fetts-armor) and [Finn, On the Run](https://swudb.com/card/twi/053/finn)), but ultimately the only `replacementImmediateEffect` that I could get to work was `null`. Interestingly, neither of the following strategies worked for me, but maybe there is someone who knows more about these that could help me understand why:
```typescript
// Did not work
AbilityHelper.immediateEffects.noAction()
// Did not work
AbilityHelper.immediateEffects.combatDamage(
(damageContext) => ({
amount: 0,
sourceAttack: damageContext.event.damageSource.attack
})
)
```
> Implement Aayla Secura, Master of the Blade

- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DisplayCardsForSelectionPrompt.ts
- test/helpers/IntegrationHelper.d.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/01_SOR/events/PrepareForTakeoff.spec.ts
- test/server/cards/01_SOR/events/Recruit.spec.ts
- test/server/cards/01_SOR/units/GrandMoffTarkinDeathStarOverseer.spec.ts
- test/server/cards/01_SOR/units/JabbaTheHuttCunningDaimyo.spec.ts
- test/server/cards/01_SOR/units/MonMothmaVoiceoftheRebellion.spec.ts
- test/server/cards/02_SHD/events/BountyPosting.spec.ts
- test/server/cards/02_SHD/events/Commission.spec.ts
- test/server/cards/02_SHD/events/RemnantReserves.spec.ts
- test/server/cards/02_SHD/events/ThisIsTheWay.spec.ts
- test/server/cards/02_SHD/units/CobbVanthTheMarshal.spec.ts
- test/server/cards/02_SHD/units/GreefKargaAffableCommissioner.spec.ts
- test/server/cards/02_SHD/units/OmegaPartOfTheSquad.spec.ts
- test/server/cards/02_SHD/upgrades/BountyHuntersQuarry.spec.ts
- test/server/cards/02_SHD/upgrades/EnticingReward.spec.ts
- test/server/cards/03_TWI/leaders/BosskHuntingHisPrey.spec.ts
Added a new "invalid" selection state to separate it out from "unselectable" which will have a different meaning in the vader / u-wing context. Switch the basic search prompts to use that by default for non-matching cards.
> Add the "invalid" selection state

- server/game/gameSystems/SelectCardSystem.ts
SelectCardSystem was checking if targets were legal for the system before checking the condition in the properties, which was causing failures in another barnch
> Fix bug in SelectCardSystem

- server/game/core/card/Card.ts
Adds controller/owner data to support proper border colors
> add controller/owner to card summary

- server/game/core/ability/AbilityContext.ts
- server/game/core/ongoingEffect/OngoingEffect.ts
- server/game/core/ongoingEffect/effectImpl/GainAbility.ts
In certain cases an ongoing effect was being activated as if it were an ability. In these cases, we were shoehorning the effect definition into `context.ability` to make everything work.
That has started causing some issues so we've added `context.ongoingEffect` as an alternative to handle those cases.
> Add `context.ongoingEffect`

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/utils/EnumHelpers.ts
We had an issue where the "in play id" which identifies the current "in play copy" of a card was not being updated correctly. When a card leaves a visible non-arena zone (e.g. discard) and goes to a hidden zone (e.g. hand), it should become a new copy of the card even if it then returns immediately to discard.
This was causing issues in the Admiral Trench case since he was seeing units that were defeated, returned to hand, and discarded again as still the same copy. This change fixes the bug in that branch.
> Fix in-play id issue for hidden zones

- server/game/cards/01_SOR/events/DontGetCocky.ts
- server/game/cards/01_SOR/events/ItBindsAllThings.ts
- server/game/cards/01_SOR/events/OverwhelmingBarrage.ts
- server/game/cards/01_SOR/events/SparkOfRebellion.ts
- server/game/cards/01_SOR/events/UWingReinforcement.ts
- server/game/cards/01_SOR/events/YoureMyOnlyHope.ts
- server/game/cards/01_SOR/units/BodhiRook.ts
- server/game/cards/01_SOR/units/C-3POProtocolDroid.ts
- server/game/cards/01_SOR/units/ChimaeraFlagshipOfTheSeventhFleet.ts
- server/game/cards/01_SOR/units/DarthVaderCommandingTheFirstLegion.ts
- server/game/cards/01_SOR/units/EmperorPalpatineMasterOfTheDarkSide.ts
- server/game/cards/01_SOR/units/EzraBridger.ts
- server/game/cards/01_SOR/units/ISBAgent.ts
- server/game/cards/01_SOR/units/LieutenantChildsenDeathStarPrisonWarden.ts
- server/game/cards/01_SOR/units/RedemptionMedicalFrigate.ts
- server/game/cards/01_SOR/units/ReinforcementWalker.ts
- server/game/cards/01_SOR/units/ViperProbeDroid.ts
- server/game/cards/02_SHD/events/CalculatedLethality.ts
- server/game/cards/02_SHD/events/MidnightRepairs.ts
- server/game/cards/02_SHD/units/BazineNetalSpyForTheFirstOrder.ts
- server/game/cards/02_SHD/units/EmboStoicAndResolute.ts
- server/game/cards/02_SHD/units/RicketyQuadjumper.ts
- server/game/cards/02_SHD/upgrades/VambraceFlamethrower.ts
- server/game/cards/03_TWI/events/UnmaskingTheConspiracy.ts
- server/game/cards/03_TWI/units/KashyyykDefender.ts
- server/game/cards/03_TWI/upgrades/Foresight.ts
- server/game/core/card/Card.ts
- test/server/cards/01_SOR/units/SparkOfRebellion.spec.ts
We have a bunch of cards that are implemented in the BE but are missing critical pieces in the FE in order to be able to function. Added a way to override the "not implemented" status manually so that testers can avoid these cards.
Updated as many cards as I'm aware of to have this marker.
> Add option to override "not implemented" status

- server/game/cards/02_SHD/events/RelentlessPursuit.ts
- server/game/cards/02_SHD/events/RuleWithRespect.ts
- server/game/cards/02_SHD/events/TakeCaptive.ts
- server/game/cards/02_SHD/events/UnexpectedEscape.ts
- server/game/cards/02_SHD/leaders/JabbaTheHuttHisHighExaltedness.ts
- server/game/cards/02_SHD/units/DiscerningVeteran.ts
- server/game/cards/02_SHD/units/EphantMonHeadOfSecurity.ts
- server/game/cards/02_SHD/units/FinalizerMightOfTheFirstOrder.ts
- server/game/cards/02_SHD/units/L3-37DroidRevolutionary.ts
- server/game/cards/02_SHD/upgrades/LegalAuthority.ts
- server/game/cards/02_SHD/upgrades/TheMandaloriansRifle.ts
- server/game/cards/03_TWI/events/PrisonerOfWar.ts
Since capture isn't implemented in the FE yet, adding the unimplemented flag manually to cards that either capture or rescue
> Flag capture and rescue effects with "not implemented" for the FE testing

- server/Util.ts
- server/game/cards/01_SOR/units/LieutenantChildsenDeathStarPrisonWarden.ts
- server/game/cards/01_SOR/units/ViperProbeDroid.ts
- server/game/core/Game.js
- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DisplayCardPrompt.ts
- server/game/core/gameSteps/prompts/DisplayCardsBasicPrompt.ts
- server/game/gameSystems/LookAtSystem.ts
- server/game/gameSystems/RevealSystem.ts
- server/game/gameSystems/ViewCardSystem.ts
- test/helpers/CustomMatchers.js
- test/helpers/IntegrationHelper.d.ts
- test/helpers/IntegrationHelper.js
- test/helpers/Util.js
- test/scenarios/timingWindows/DefeatTiming.spec.ts
- test/server/cards/01_SOR/units/DarthVaderCommandingTheFirstLegion.spec.ts
- test/server/cards/01_SOR/units/InfernoFourUnforgetting.spec.ts
- test/server/cards/01_SOR/units/LieutenantChildsenDeathStarPrisonWarden.spec.ts
- test/server/cards/01_SOR/units/R2D2IgnoringProtocol.spec.ts
- test/server/cards/01_SOR/units/ViperProbeDroid.spec.ts
- test/server/cards/02_SHD/units/CobbVanthTheMarshal.spec.ts
- test/server/cards/03_TWI/events/WartimeProfiteering.spec.ts
Beginning the process of refactoring for every lookat / reveal effect to use the display prompt instead of relying on text messages. Since there are a lot of cards that need to be updated and many of them are special cases, we are adding an optional property that enables the prompt in the `lookAt()` and `reveal()` functions. This will be removed once all cards are ported over.
Converted VPD and Childsen to use the new prompt system.
> Add optional prompt support for "basic" lookat / reveal case

- server/game/cards/03_TWI/units/PerilousPosition.ts
- server/game/core/card/UpgradeCard.ts
- test/server/cards/03_TWI/units/PerilousPosition.spec.ts
While implementing Bravado, I discovered there was a bug for Perilous Position where if the unit was defeated by the upgrade, an exception would be thrown when the upgrade tried to resolve the exhaust portion of the ability. Since the unit was immediately defeated, when the exhaust resolved the unit and upgrade would both already be in the discard. The simplest solution was to remove the contract checks and let the ability fizzle due to not having a target.
> Fix bug with Perilous Position

- server/game/cards/01_SOR/events/SparkOfRebellion.ts
- server/game/cards/01_SOR/units/ReinforcementWalker.ts
- server/game/cards/02_SHD/events/BountyPosting.ts
- server/game/cards/02_SHD/units/CobbVanthTheMarshal.ts
- server/game/core/ability/AbilityContext.ts
- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DisplayCardsForSelectionPrompt.ts
- server/game/core/gameSteps/prompts/DisplayCardsWithButtonsPrompt.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/LookAtSystem.ts
- server/game/gameSystems/LookMoveDeckCardsTopOrBottomSystem.ts
- server/game/gameSystems/RevealSystem.ts
- server/game/gameSystems/SearchDeckSystem.ts
- server/game/gameSystems/ViewCardSystem.ts
- test/server/cards/01_SOR/units/InfernoFourUnforgetting.spec.ts
- test/server/cards/01_SOR/units/ReinforcementWalker.spec.ts
- test/server/cards/01_SOR/units/SparkOfRebellion.spec.ts
- test/server/cards/02_SHD/events/BountyPosting.spec.ts
- test/server/cards/02_SHD/units/KylosTieSilencerRuthlesslyEfficient.spec.ts
Now that we have a framework for how the DisplayCardPrompt stuff will work, expanded the underlying system for lookAt / reveal to be able to handle effects of the form "look at [cards] and do [X]." Since in those cases we want to tie together the view and the action into one prompt, we need to be able to declare this using the appropriate systems.
Ported Reinforcement Walker and Spark of Rebellion onto the new framework as a pilot, will do other cards progressively.
> Expand ViewCardSystem to support new prompt types

- server/game/cards/01_SOR/units/LieutenantChildsenDeathStarPrisonWarden.ts
- server/game/core/Game.js
Added an exception guard for token generators to let us know if invalid token data is provided. Also removed the unnecessary unimplemented override on Childsen.
> Better guard for token generators

- Dockerfile
- server/utils/cardData/RemoteCardDataGetter.ts
replace '#' with '%23' in remote card getter url
Set deocker image environment env to production
> make card data url web safe

- server/game/cards/01_SOR/events/YoureMyOnlyHope.ts
- test/helpers/CustomMatchers.js
- test/server/cards/01_SOR/events/YoureMyOnlyHope.spec.ts
- test/server/cards/03_TWI/units/LuxBonteriRenegadeSeparatist.spec.ts
| Play for Discount | Play for Free |
| <img src="https://github.com/user-attachments/assets/7da107cb-5d7c-4df1-9c39-11b66c8d35c6" /> | <img src="https://github.com/user-attachments/assets/baa30370-7e94-430f-8bea-f87d8180f69e" /> |
> Update display prompt for You're My Only Hope

- server/game/core/utils/Contract.ts
- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- server/socket.js
- Adds a simple error handler middleware to api routes
- Adds async error handling for websocket messages
- Switches Contracts failure mode to Throw errors instead of AssertionErrors in production. We can change this to always be thrown errors if we want but I thought it might be useful to maintain the severity of errors when working in local.
> Handle route errors and ws async errors

- server/game/core/Game.js
- server/game/core/Player.js
- server/game/core/gameSteps/ActionWindow.js
- server/game/core/gameSteps/abilityWindow/TriggerWindowBase.ts
- test/helpers/CustomMatchers.js
- test/helpers/PlayerInteractionWrapper.js
- test/server/core/gameSteps/regroupWindow/RegroupPhase.spec.ts
SWU rules state that outside of the action phase, the "active player" is whoever has initiative. We were not doing this correctly and causing errors if multiple abilities triggered in the same window in the regroup phase.
Addresses https://github.com/SWU-Karabast/forceteki/issues/662
> Correct handling of "active player" in regroup phase

- server/game/gameSystems/DelayedEffectSystem.ts
- test/server/cards/01_SOR/leaders/HanSoloAudaciousSmuggler.spec.ts
Fixes https://github.com/SWU-Karabast/forceteki/issues/580
The DelayedEffectSystem had a default value of `limit` which was an actual `AbilityLimit` object that would be shared across all instances of DelayedEffectSystem and therefore get fully spent the first time a delayed effect triggers
> Fix Han1 repeated trigger bug

- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/event/EventWindow.ts
- test/server/core/abilities/keyword/Bounty.spec.ts
Fixes https://github.com/SWU-Karabast/forceteki/issues/607
Bounties gained by leaders were not resolving because it was checking if the card was a unit first, and the leader had already moved to the base zone. Added a pre-event emit to be used for this case.
> Fix bug with bounties on leaders

- server/game/core/card/Card.ts
- server/utils/cardData/CardDataInterfaces.ts
- server/utils/deck/DeckValidator.ts
The "not implemented" auto-check wasn't accounting for the new pilot text field. Added that and also automatically marks leaders as requiring implementation.
> Add "not implemented" warning support for piloting cards

- server/game/core/Game.js
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/gameSteps/AbilityResolver.js
- test/server/actions/UnitAttack.spec.ts
- test/server/cards/01_SOR/events/TacticalAdvantage.spec.ts
- test/server/core/card/Upgrade.spec.ts
Re-added the Cancel button for certain common and simple scenarios. Basically any ability which uses targeting and is not a "nested" ability (i.e., one ability triggers another) can be safely cancelled.
Will add deeper support in a further PR.
> Better cancel button support

- server/game/cards/04_JTL/bases/DataVault.ts
- server/game/cards/04_JTL/bases/ThermalOscillator.ts
- server/utils/deck/DeckValidator.ts
Added basic support for Data Vault and Thermal Oscillator so they don't cause deck import errors. They still need tests, but that's blocked by adding test infra for the deck validator generally.
Also removed the SB size restriction on Next Set Preview and Open formats after internal discussion.
> Support deck size bases and remove SB size restriction in non-Premier formats

- server/game/cards/01_SOR/units/HomeOneAllianceFlagship.ts
- test/server/cards/01_SOR/units/HomeOneAllianceFlagship.spec.ts
Fixing Home One issue. It should not give +1 restore to itself.
> fix home one friendly restore

- eslint.config.mjs
- server/game/abilities/keyword/BountyAbility.ts
- server/game/core/Constants.ts
- server/game/core/Game.js
- server/game/core/GamePipeline.ts
- server/game/core/ability/CardAbilityStep.js
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/ability/TriggeredAbility.ts
- server/game/core/gameSteps/BaseStepWithPipeline.ts
- server/game/core/gameSteps/abilityWindow/TriggerWindowBase.ts
- test/server/cards/02_SHD/units/QiraPlayingHerPart.spec.ts
Fix for Qira Playing Her Part (and any Then usage). meetRequirements now only checks substeps for then/ifYouDo.
Additionally, I added some limited "debug" flags to the Game class and flag checks inside of the GamePipeline, intended for manual usage only. Essentially this allowed me to take a side-by-side comparison of the pipeline steps with and w/o a hand of cards (WinMerge for the win) to see where it diverged.
LMK if you'd prefer to remove the debug, I added some safety's but might still be good to keep it out unless we could enforce the flags at build time, IE ignore debug calls entirely unless we are running a single unit test.
The above example would enable the flag to write out each pipeline step, then disable it again, so it's scoped to specific actions. Also prevents people from …
> SubStep Check Fixes

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Added a fix for requeuing. The problem occurred when a user refreshed the page when matched with a player. Their socket was reinitialized and were added to the lobby without a requeue event listener.
> #QuickMatchmakingRequeueFix

- server/game/cards/04_JTL/leaders/RioDurantWisecrackingWheelman.ts
- test/server/cards/04_JTL/leaders/RioDurantWisecrackingWheelman.spec.ts
> Implementing Rio Durant, Wisecracking Wheelman

- server/game/cards/03_TWI/upgrades/ShadowedIntentions.ts
- server/game/cards/03_TWI/upgrades/SquadSupport.ts
- server/game/cards/04_JTL/units/ChewbaccaFaithfulFirstMate.ts
- server/game/cards/04_JTL/units/JarekYeagerCoordinatingWithTheResistance.ts
- server/game/cards/04_JTL/units/R2D2Artooooooooo.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
Fixed a couple of subtle issues related to various effects granting a constant ability to the attached unit.
- The Piloting helper was not correctly adding a zone filter to the `gainCondition` check, which can result in exceptions happening in some cases
- In several cases we had mis-implemented an ability from an upgrade where it says the attached unit _gains_ a constant ability targeting itself, and were instead using the upgrade as the ability source. This came up during testing for Kazuda since it has implications for how his ability impacts those cards. Should be fixed now.
> Fixes to various "gain constant ability" effects

- server/game/cards/01_SOR/leaders/IdenVersioInfernoSquadCommander.ts
- server/game/cards/01_SOR/units/GideonHaskRuthlessLoyalist.ts
- test/server/cards/01_SOR/leaders/IdenVersioInfernoSquadCommander.spec.ts
- test/server/cards/01_SOR/units/GideonHaskRuthlessLoyalist.spec.ts
They were both triggering when a pilot (upgrade) was defeated.
| Iden Versio | Gideon Hask |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/6e1205fb-4d97-4feb-860b-43a686695ec0) | ![image](https://github.com/user-attachments/assets/c949a8fa-77b7-4d1d-9710-7b0c2257a225) |
> Fix Gideon Hask and Iden Versio triggers with pilots

- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/MoveCardSystem.ts
MoveCardSystem had a very strict contract check in canAffect making it illegal to even ask if a card could be moved to an illegal zone. This was triggering some hard-to-identify errors in the logs and is probably too strong of a check anyway. Reduced it to just returning `false` in that case.
> Relax MoveCard contract check

- server/game/cards/01_SOR/leaders/CassianAndorDedicatedToTheRebellion.ts
- server/game/cards/04_JTL/leaders/BobaFettAnyMethodsNecessary.ts
- server/game/core/ability/TriggeredAbilityContext.ts
- server/game/core/ability/abilityTargets/PlayerTargetResolver.ts
- server/game/core/gameSteps/abilityWindow/TriggerWindowBase.ts
- test/server/cards/04_JTL/events/PlanetaryBombardment.spec.ts
- test/server/cards/04_JTL/events/TorpedoBarrage.spec.ts
- test/server/cards/04_JTL/leaders/BobaFettAnyMethodsNecessary.spec.ts
Made the following prompts a little clearer:
- For indirect damage, added the ability title to the prompt and clarified that you are choosing the targeted player
- For Boba leader, added support for consolidating multiple triggers down to one
> Improve some common prompt issues

- server/game/cards/03_TWI/events/ConsolidationOfPower.ts
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- test/server/cards/02_SHD/units/FennRauProtectorOfConcordDawn.spec.ts
- test/server/cards/02_SHD/upgrades/RichReward.spec.ts
- test/server/cards/03_TWI/events/ConsolidationOfPower.spec.ts
We were showing both "Pass" and "Choose no target" on some prompts, which was pushing the "Done" button under the hand. Fixed this in the card target resolver and fixed the Consolidation of Power implementation to have the correct UX flow.
> Fix Rich Reward

- server/game/actions/PlayEventAction.ts
- server/game/cards/04_JTL/leaders/KazudaXionoBestPilotInTheGalaxy.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/gameSystem/LastingEffectPropertiesBase.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
- server/game/gameSystems/CardPhaseLastingEffectSystem.ts
- server/game/gameSystems/CardRoundLastingEffectSystem.ts
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/SelectCardSystem.ts
Did some light cleanup on the game message system and made it so that the Kazuda effect now says the name of the target, as well as "basic" damage cases in which only a single target is being damaged with a fixed amount (eg Daring Raid, basic attacks).
> Update Kazuda game message and basic damage messages

- server/game/core/gameSteps/abilityWindow/TriggerWindowBase.ts
- test/server/cards/03_TWI/leaders/JangoFettConcealingTheConspiracy.spec.ts
There was an issue where if the same ability was triggered multiple times in the same window (e.g. Jango leader) then abilities would resolve in random order when chosen from the trigger menu
> Fix issue with ordering on multi-trigger for the same ability

- server/game/cards/02_SHD/events/EndlessLegions.ts
- test/server/cards/02_SHD/events/EndlessLegions.spec.ts
Updated code with canChooseNoCards: true,
and updated test for player to choose no target
> endlessLegions

- server/logger.ts
Added a switch to the logger to do literal newlines for CloudWatch when running under the AWS environment.  This will collapse a stack trace into a singular entries with explicit new line characters (hopefully rendering correctly when selected via LogInsight)
> Logger switch for CloudWatch newlines

- server/game/IDamageOrDefeatSource.ts
- server/game/cards/04_JTL/leaders/LukeSkywalkerHeroOfYavin.ts
- server/game/cards/04_JTL/units/ChewbaccaFaithfulFirstMate.ts
- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/gameSystems/DefeatCardSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/04_JTL/leaders/LukeSkywalkerHeroOfYavin.spec.ts
- test/server/cards/04_JTL/units/ChewbaccaFaithfulFirstMate.spec.ts
Chewbacca pilot was incorrectly preventing defeat effects by the owner's opponent even when stolen. Luke was not preventing defeat effects again himself correctly. Solved both of these by moving them over to being replacement effects, which is what FFG says they are supposed to be with a recent clarification.
> Fix prevention abilities on Chewbacca pilot and Luke pilot leader

- server/game/core/ability/KeywordHelpers.ts
- test/server/core/abilities/keyword/Piloting.spec.ts
The parser for piloting abilities was requiring aspect costs to be present, but for "neutral" cards there might not be aspect costs. This was causing Sullustan Spacer to not read as having a piloting ability.
> Sullustan Spacer fix

- server/game/core/Game.js
- server/game/core/card/baseClasses/InPlayCard.ts
- test/server/core/card/UniqueRule.spec.ts
> Fix uniqueness check when multiple unique units enter play

- server/game/core/Constants.ts
- server/game/core/Game.js
- server/game/core/GameObjectBase.ts
- server/game/core/GamePipeline.ts
- server/game/core/GameStateManager.ts
- server/game/core/Player.ts
- server/game/core/card/Card.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/gameSteps/IStep.ts
- server/game/core/gameSteps/phases/ActionPhase.ts
- server/game/core/gameSteps/phases/Phase.ts
- server/game/core/utils/Contract.ts
- server/game/core/utils/Helpers.ts
- server/game/core/zone/SimpleZone.ts
- server/utils/deck/Deck.ts
- test/helpers/IntegrationHelper.d.ts
- test/helpers/IntegrationHelper.js
- test/helpers/PlayerInteractionWrapper.js
- test/scenarios/undo/Undo.spec.ts
- test/server/core/gameSteps/AbilityResolver.spec.ts
* A number of Game.js fields moved into a state object
* Player Decklist converted to use GameObjectRef and moved into state
* Card.parentCard converted to GameObjectRef and moved into state
* Fixed, then disabled the "filter card from list" in Game.js, it wasn't doing anything before so it's disabled for now.
* Converted undo test to a custom global uit function
* Added a JS private #experimental object in the Game for flagging the system to use undo logic. That way I can enable it in tests now and in the future for local builds only.
Soooo I made some methods public in ActionPhase to make clearing the ActionPhase possible. It's a little horrifying but it did work for tests. And the way I clear the pipeline also was quick and dirty.
the new uit function only works with tests that do the …
> Game and other state, and unit test improvements

- server/game/core/card/UpgradeCard.ts
- server/gamenode/Lobby.ts
Couple fixes related to an out-of-memory failure that happened recently:
- Added a missing check to upgrade constant abilities
- Lobby will now track the number of errors for a given request and bail out if it gets too high
> Fix issues related to OOM crash

- server/game/abilities/keyword/exploit/ExploitCostAdjuster.ts
- server/game/abilities/keyword/exploit/MergedExploitCostAdjuster.ts
- server/game/core/Game.js
- server/game/core/cost/CostAdjuster.ts
- test/server/cards/03_TWI/leaders/CountDookuFaceOfTheConfederacy.spec.ts
Fixes a bug discovered with Count Dooku where hitting the "cancel" button at the exploit trigger stage would cause the cost adjuster to break _if_ the unit didn't already have its own exploit
> Better cancel handling for floating cost adjusters

- server/game/cards/02_SHD/upgrades/BountyHuntersQuarry.ts
- server/game/core/ability/PlayerAction.js
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/gameSystems/PlayCardSystem.ts
- test/helpers/IntegrationHelper.d.ts
- test/helpers/IntegrationHelper.js
- test/server/actions/UnitAttack.spec.ts
- test/server/cards/01_SOR/bases/EnergyConversionLab.spec.ts
- test/server/cards/01_SOR/events/Command.spec.ts
- test/server/cards/01_SOR/events/ForACauseIBelieveIn.spec.ts
- test/server/cards/01_SOR/events/SuperlaserBlast.spec.ts
- test/server/cards/01_SOR/leaders/SabineWrenGalvanizedRevolutionary.spec.ts
- test/server/cards/01_SOR/units/EmperorPalpatineMasterOfTheDarkSide.spec.ts
- test/server/cards/02_SHD/events/MidnightRepairs.spec.ts
- test/server/cards/02_SHD/units/OmegaPartOfTheSquad.spec.ts
- test/server/cards/02_SHD/upgrades/BountyHuntersQuarry.spec.ts
- test/server/cards/03_TWI/leaders/AnakinSkywalkerWhatItTakesToWin.spec.ts
- test/server/cards/03_TWI/leaders/CountDookuFaceOfTheConfederacy.spec.ts
- test/server/cards/03_TWI/units/SubjugatingStarfighter.spec.ts
- test/server/cards/04_JTL/units/BlueLeaderScarifAirSupport.spec.ts
- test/server/cards/04_JTL/units/TheStarhawkPrototypeBattleship.spec.ts
- test/server/core/Game.spec.ts
- test/server/core/gameSteps/regroupWindow/RegroupPhase.spec.ts
- test/server/gameSystems/DrawSystem.spec.ts
Fixes #1067 
- Removed phase check in `PlayerAction.js` because it was preventing certain actions from being executed off a triggered ability during the regroup phase
- Added a simple case of collecting Bounty Hunter's Quarry during the regroup phase to `BountyHuntersQuarry.spec.ts`
- Added several more complex cases of chains of triggered abilities (all stemming from BHQ) to `RegroupPhase.spec.ts`
> [Bugfix] Bounty Hunter's Quarry can resolve during the regroup phase

- server/game/Interfaces.ts
- server/game/cards/02_SHD/units/LurkingTIEPhantom.ts
- server/game/cards/03_TWI/upgrades/ShadowedIntentions.ts
- server/game/core/card/UpgradeCard.ts
- test/server/cards/02_SHD/units/LurkingTIEPhantom.spec.ts
- test/server/cards/03_TWI/upgrades/ShadowedIntentions.spec.ts
- test/server/cards/04_JTL/events/NoGloryOnlyResults.spec.ts
Also partially updates Lurking TIE Phantom to use replacement effects to prevent defeat and capture by enemy card abilities. The damage prevention is still using ongoing effects because more work is needed to update replacement effects to work with damage prevention (#820).
Fixes #1131
> Update Shadowed Intentions to use replacement effects

- server/game/abilities/EpicActionAbility.ts
- server/game/cards/01_SOR/bases/EnergyConversionLab.ts
- server/game/cards/01_SOR/leaders/ChewbaccaWalkingCarpet.ts
- server/game/cards/02_SHD/events/TimelyIntervention.ts
- server/game/cards/02_SHD/leaders/FennecShandHonoringTheDeal.ts
- server/game/cards/02_SHD/units/IG-11ICannotBeCaptured.ts
- server/game/cards/05_LOF/events/AsIHaveForeseen.ts
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/ability/abilityTargets/TargetResolver.ts
- server/game/core/card/BaseCard.ts
- server/game/core/gameSystem/AggregateSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/SequentialSystem.ts
- server/game/gameSystems/SimultaneousOrSequentialSystem.ts
- server/game/gameSystems/SimultaneousSystem.ts
- test/server/cards/01_SOR/bases/EnergyConversionLab.spec.ts
- test/server/cards/01_SOR/leaders/ChewbaccaWalkingCarpet.spec.ts
- test/server/cards/02_SHD/events/TimelyIntervention.spec.ts
- test/server/cards/02_SHD/leaders/FennecShandHonoringTheDeal.spec.ts
Apply a fix similar to #1160 to other cards like Timely Intervention. It also fixes a contract assertion that was happening if you selected `Choose nothing` when using one of these abilities.
Fixes #1086
> Fix cards similar to Timely Intervention

- server/game/core/card/propertyMixins/UnitProperties.ts
The new attacking / defending properties were breaking for pilots due to property checks
> Pilot hotfix

- server/game/Interfaces.ts
- server/gamenode/Lobby.ts
- server/utils/bugreport/BugReportHandler.ts
Updated the bug report to take in the screen resolution and viewport for helping debug  FE issues.  Helpful to see what sort of device "roughly" they are using when complaining about UI features.  Strictly captures the physical screen resolution and then viewport of the game within the browser 
Here is a new bug report from an iphone in landscape
Here it is in portrait mode
Here is the FE sending the old message w/o screen resolution and viewport set -- proving its still backward compatible and can read the old messages
> Added screen resolution and viewport to the bug report entries

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- server/gamenode/QueueHandler.ts
Added logging for the socket id on connect / disconnect events to help catch potential issues related to multiple open connections for the same user.
If a user connects with a new socket, we now disconnect the previous one before attaching the new one to decrease the likelihood of having multiple open. Also added checks to make sure that disconnect events are ignored if they are for sockets other than the most recently connected one.
> Logging and better disconnect management for sockets

- server/game/cards/03_TWI/events/ImproprietyAmongThieves.ts
- test/server/cards/03_TWI/events/ImproprietyAmongThieves.spec.ts
Fixes #1165
- Event fizzles if there is no ready friendly non-leader unit
- Event fizzles if there is no ready enemy non-leader unit
- A unit is defeated after exchange of control
- A unit is returned to hand after exchange of control
- A unit changes control again after initial exchange of control
- Both units are defeated, one of which moves to the resource zone
- Both units are returned to hand
> Fix issues with Impropriety Among Thieves

- server/game/core/Player.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/gameSystems/DrawSystem.ts
- server/game/gameSystems/TakeControlOfUnitSystem.ts
- test/server/cards/01_SOR/events/ChangeOfHeart.spec.ts
- test/server/core/card/UniqueRule.spec.ts
- test/server/gameSystems/DrawSystem.spec.ts
Fixes #1284
| Uniqueness Rule | Leader Change Control | Draw from empty deck |
| :---: | :---: | :---: |
|<img width="265" alt="Screenshot 2025-05-24 at 9 34 57 AM" src="https://github.com/user-attachments/assets/69c09fc4-b69e-4ede-9f49-992e589e83b6" /> | <img width="254" alt="Screenshot 2025-05-24 at 9 50 17 AM" src="https://github.com/user-attachments/assets/204ba851-a015-4e42-af91-0cd9eb54990d" /> | <img width="243" alt="Screenshot 2025-05-24 at 9 50 40 AM" src="https://github.com/user-attachments/assets/c0fefc11-d28f-4ee8-ad35-6f2a9d9e3882" /> |
| <img width="279" alt="Screenshot 2025-05-24 at 9 30 16 AM" src="https://github.com/user-attachments/assets/e9476f6e-57d5-4d10-b980-0f78625d3116" /> | | |
> Improve game chat logs for Game Rule effects

- server/game/core/actionTimer/IActionTimer.ts
- server/game/core/actionTimer/StandardActionTimer.ts
- server/game/core/gameSteps/prompts/DistributeAmongTargetsPrompt.ts
- server/game/core/gameSteps/prompts/UiPrompt.ts
Temporarily extending turn timer during distribution prompt to 2min to get around the issue where the messages are resetting the prompt
> Extend turn timer during distribution prompt

- server/game/cards/02_SHD/leaders/DoctorAphraRapaciousArchaeologist.ts
- server/game/cards/03_TWI/units/JarJarBinksFoolishGungan.ts
- server/game/core/Constants.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/RandomSelectionSystem.ts
- test/server/cards/02_SHD/leaders/DoctorAphraRapaciousArchaeologist.spec.ts
- test/server/cards/03_TWI/units/JarJarBinksFoolishGungan.spec.ts
Card abilities are evaluated many times throughout the steps of the ability resolution. For example, they could be evaluated separately while resolving the ability and generating an effect message for the ability. This created issues where there was a discrepancy between game state and the game logs.
This PR adds a `RandomSelectionSystem` so card abilities can reliably produce a random result that is only evaluated once during ability resolution. This system can take an array of targets from its surrounding context and will randomly select `count` targets for its inner system.
Fixes #1329 
| Doctor Aphra | Jar Jar Binks |
| <img width="259" alt="Screenshot 2025-06-04 at 5 07 19 PM" src="https://github.com/user-attachments/assets/7c30324b-0792-452e-b6d4-4a8fa61d21be" /> | …
> Add a RandomSelectionSystem for reliable randomization during ability resolution

- server/game/cards/05_LOF/events/Shatterpoint.ts
- test/server/cards/05_LOF/events/Shatterpoint.spec.ts
Using the `ChooseModalEffectsSystem` means we get the player's choice in the chat logs:
> Update Shatterpoint to use ChooseModalEffectsSystem

- server/game/cards/02_SHD/upgrades/BobaFettsArmor.ts
- server/game/gameSystems/DamageSystem.ts
When running the tests, I noticed that Boba Fett's Armor was throwing an error. I changed the implementation to do something similar to Finn and Shien Flurry instead.
> Fix Boba Fett's Armor

- server/game/gameSystems/DistributeAmongTargetsSystem.ts
- test/server/cards/01_SOR/events/OverwhelmingBarrage.spec.ts
The fix in #1420 wasn't working correctly with shields.
> Better fix for damage distribution with replacement effect

- server/game/cards/05_LOF/events/FlightOfTheInquisitor.ts
- test/server/cards/05_LOF/events/FlightOfTheInquisitor.spec.ts
Flight of the Inquisitor would only let the player choose from the opponent's discard if it was non-empty
> Fix controller issue with Flight of the Inquisitor

- server/game/cards/03_TWI/units/CountDookuFallenJedi.ts
- test/server/cards/03_TWI/units/CountDookuFallenJedi.spec.ts
Per user request: 
> When exploiting 2 units with Dooku, there is no way to know which unit's power is being used
> I reallllly wish it said "Deal X damage" when I'm choosing my targets
--------
> Call out damage amount and exploited unit's title in TWI Count Dooku's ability prompt

- server/game/core/PlayerPromptState.ts
- server/game/core/gameSteps/prompts/ResourcePrompt.ts
The gamestate changes made it so that when you click "Done" while resourcing, the chosen cards appear as unselected. Fixed things so that (a) we always send "selected: true" even if selectable is false, and (b) we now send promptType: resource for the player who is waiting on the opponent
> Bug fixes in FE state related to resourcing

- server/game/cards/01_SOR/leaders/CassianAndorDedicatedToTheRebellion.ts
- server/game/stateWatchers/DamageDealtThisPhaseWatcher.ts
- test/server/cards/01_SOR/leaders/CassianAndorDedicatedToTheRebellion.spec.ts
This PR has a couple fixes related to the SOR Cassian Andor leader:
- The leader and unit side abilities should only count damage dealt to an _enemy_ base
- The unit side ability should be optional
- The `DamageDealtThisPhaseWatcher` now tracks the correct damage amount for overhwhelm damage (previously it was coming through as `undefined`)
> [Bugfix] Cassian Andor leader & DamageDealtThisPhaseWatcher

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
Few small tweaks to patch over some potential problems that might be causing the queueing issues for people on unstable internet connections.
I suspect that what's going on is that if any disconnects happen during the handoff from the queue to the lobby, our user connection flag gets messed up and erroneously marks the user as disconnected. Then, they don't receive lobby state updates, so the FE never updates and the server thinks they left.
The changes I made to try and smooth this over are:
- Changed the state-send methods to check the underlying socketio connection flag, as that is much more reliable. If this seems to work better then we can plan to move off of our manual connection flag completely.
- Added a callback on the state-send function that will mark the user's status as …
> Connection improvements during matchmaking countdown

- server/game/TargetInterfaces.ts
- server/game/cards/01_SOR/events/SearchYourFeelings.ts
- server/game/cards/02_SHD/events/BountyPosting.ts
- server/game/cards/04_JTL/units/AnnihilatorTaggesFlagship.ts
- server/game/core/ability/abilityTargets/DropdownListTargetResolver.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PlayMultipleCardsFromDeckSystem.ts
- server/game/gameSystems/SearchDeckSystem.ts
- server/game/gameSystems/SearchEntireDeckSystem.ts
- test/server/cards/01_SOR/events/SearchYourFeelings.spec.ts
- test/server/cards/02_SHD/events/BountyPosting.spec.ts
- test/server/cards/03_TWI/leaders/PreVizslaPursuingTheThrone.spec.ts
- test/server/cards/03_TWI/units/Clone.spec.ts
- test/server/cards/04_JTL/units/AnnihilatorTaggesFlagship.spec.ts
We have a UI issue currently where the card display prompt can't show the entire deck since it doesn't have a scroll option, so it can overwhelm the screen.
Made some adjustments to the cards that need to search the whole deck to make them at least playable for now:
- Bounty Posting: now will only show the selectable cards from the deck instead of the whole deck
- Annihilator: already had a similar workaround to Bounty Posting, just made it _slightly_ less incorrect in that the player can now choose how many copies to remove from the deck
- Search Your Feelings: now uses a dropdown list of card names instead the card display. there's a little bit of a rules issue where right now we can't offer the option to choose no card, since the dropdown UI doesn't have support for extra buttons. Will …
> Fix cards that search entire deck

- server/game/cards/02_SHD/events/CalculatedLethality.ts
- test/server/cards/02_SHD/events/CalculatedLethality.spec.ts
Fixes #1534
Calculated Lethality was causing a server error when there were no units to target because the `lastKnownInformation` was undefined.
> Fix server error with Calculated Lethality

- server/game/core/card/baseClasses/InPlayCard.ts
- test/server/core/card/UniqueRule.spec.ts
When a second copy of a unique upgrade is played, the user must choose to defeat one. If the user chooses to defeat the newly played copy, we incorrectly fail to trigger any When Played abilities on the upgrade (Luke's Lightsaber, Mandalorian's Rifle, etc), because the ability cannot access the LKI to determine if it was attached to the named unit.
This commit temprarily fixes the issue in the case where the new copy is played on the same unit as the old copy. For this case, we will automatically defeat the oldest copy, allowing the new copy to resolve its When Played ability.
This is a temporary fix for #1491. A long-term fix would allow the card ability to automatically use LKI if the card is no longer in play.
> Temporary fix for unique upgrades with When Played abilities

- server/game/core/GameObjectBase.ts
- server/game/core/ability/AbilityLimit.ts
- server/game/core/ability/TriggeredAbility.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/core/snapshot/GameStateManager.ts
GameObjects that registered event listeners might leave state hanging if they are removed from the GameObject list completely instead of being rolled back to an "unregistered" state. Fixed this by adding a cleanup method that is called when GOs are removed completely, which handles unregistration.
Also cleaned up a couple N^2 `find()` operations which improved undo test time by 3x.
> Undo: fix event listener cleanup for rolled-back objects

- server/gamenode/GameServer.ts
Added cpu stats logging on a 30 second interval using the node.js process utils
Output looks like this next to HeapStats
```
2025-08-06T21:44:06.131Z [info]: [HeapStats] Used: 30.6MB / 33.7MB (0.7% of 4144.0MB limit) | Total physical usage: 74.0MB | System free: 12.71GB
2025-08-06T21:44:06.131Z [info]: [CpuStats] Total Usage: 0.0% (User: 0.0%, System: 0.0%) | System Cores: 16
```
Now with EventLoopStats
```
2025-08-07T01:36:12.396Z [info]: [HeapStats] Used: 30.2MB / 33.7MB (0.7% of 4144.0MB limit) | Total physical usage: 74.3MB | System free: 11.79GB
2025-08-07T01:36:12.397Z [info]: [CpuStats] Total Usage: 0.0% (User: 0.0%, System: 0.0%) | System Cores: 16
2025-08-07T01:36:12.397Z [info]: [EventLoopStats] Event Loop Utilization: 0.2% | Event Loop Duration (ms): min: 13.6, P50: 15.3, P90: …
```
> CPU stats logging

- server/game/cards/05_LOF/leaders/KyloRenWereNotDoneYet.ts
- test/server/cards/05_LOF/leaders/KyloRenWereNotDoneYet.spec.ts
Currently, the user is presented with all triggers for Kylo at the end of his deployment, rather than in sequence as they are played. This PR should fix that and adds a test to ensure multiple triggers resolve as played
> Fix LOF Kylo Deploy triggers not being nested

- package-lock.json
- package.json
- server/game/core/GameObjectBase.ts
- server/game/core/GameObjectUtils.ts
- server/game/core/ongoingEffect/effectImpl/DetachedOngoingEffectValueWrapper.ts
- server/game/core/ongoingEffect/effectImpl/DynamicOngoingEffectImpl.ts
- server/game/core/ongoingEffect/effectImpl/OngoingEffectImpl.ts
- server/game/core/ongoingEffect/effectImpl/OngoingEffectValueWrapper.ts
- server/game/core/ongoingEffect/effectImpl/StaticOngoingEffectImpl.ts
- server/game/core/snapshot/GameStateManager.ts
- server/game/core/snapshot/SnapshotFactory.ts
- server/game/core/snapshot/SnapshotInterfaces.ts
- server/game/core/stateWatcher/StateWatcherRegistrar.ts
- server/game/core/utils/TypeHelpers.ts
Moved from using structuredClone to using v8.serialization. Also eliminated some additional bulk copy usages.
This includes V2 of @undoMap, which no longer requires the type to be Readonly. Still a bit experimental but it should cut down on creating new objects every time want to update a map.
> Feature: Undo V8 Serialization

- server/game/core/attack/Attack.ts
- server/game/gameSystems/AttackStepsSystem.ts
- test/server/actions/UnitAttack.spec.ts
Found that one cause of some of the game crashes is that when an enemy unit has become captured by another enemy unit, the attack logic handles it incorrectly and tries to create a hypothetical attack targeting the captured unit. This causes a targeting exception, which gets hit repeatedly very fast and exceeds the server error limit.
> Fix capture-related exception causing server issues

- server/game/core/Game.js
- server/game/core/snapshot/GameStateManager.ts
- server/game/core/snapshot/container/SnapshotArray.ts
- server/game/core/snapshot/container/SnapshotContainerBase.ts
- server/game/core/snapshot/container/SnapshotHistoryMap.ts
- server/game/core/snapshot/container/SnapshotMap.ts
- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
Added a hidden query parameter `?undoTest=true` which will enable undo in private games only. FE PR: https://github.com/SWU-Karabast/forceteki-client/pull/452
Added some piping to support this, as well as a few minor UX and polish things that are required for this test. Includes:
- There was an N^2 operation during rollback, made it more efficient
- Game chat message for undo success or failure
- Better error handling of undo failures in general
- Will attempt to roll back to the prior state if a rollback fails
> Enable undo test mode in prod

- server/game/cards/04_JTL/units/SeasonedFleetAdmiral.ts
- test/server/cards/04_JTL/units/SeasonedFleetAdmiral.spec.ts
> [Bugfix] Prevent Seasoned Fleet Admiral's ability from double-triggering

- server/game/cards/03_TWI/leaders/MaceWinduVaapadFormMaster.ts
- server/game/core/Constants.ts
- server/game/core/Game.js
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/gameSteps/AbilityResolver.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/core/snapshot/GameStateManager.ts
- server/gamenode/Lobby.ts
- test/server/cards/03_TWI/leaders/MaceWinduVaapadFormMaster.spec.ts
The Mace Windu leader's `thenCondition` was missing a null check that could cause severe game crashes. Fixed this issue and changed the severe error handling to allow the game to potentially recover in simple cases like this one.
> Fix Mace Windu leader issue causing game crashes
