SWU-Karabast/forceteki

- bin/fetchdata.js
- server/game/actions/PlayUnitAction.ts
- server/game/actions/TriggerAttackAction.ts
- server/game/core/gameSteps/phases/ActionPhase.ts
- server/game/core/gameSteps/phases/RegroupPhase.ts
- server/game/core/gameSteps/phases/SetupPhase.ts
- server/game/core/gameSteps/prompts/GameWonPrompt.js
- server/game/core/gameSteps/prompts/ResourcePrompt.js
- server/game/gameSystems/AttackSystem.ts
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/DefeatCardSystem.ts
- server/game/gameSystems/ExhaustSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PutIntoPlaySystem.ts
- test/server/card/PlayUnitFromHand.spec.js
- test/server/card/UnitAttack.spec.js
Adding some of the basic pieces for SWU game rules:
- Setup phase and action phase logic
- Prompt for resourcing
- Play unit from hand (with tests)
- Attack with unit (with tests)
- Card definitions download from the official website
> Phases, play unit, attack

- server/game/core/Player.js
- server/game/core/ability/CardAbility.js
- server/game/core/card/Card.ts
Converted some bookmarks I have to TODO EVENT comments for easier tracking
> Add todo comments for events

- server/game/cardImplementations/01_SOR/AvengerHuntingStarDestroyer.ts
- server/game/core/Game.js
- server/game/core/ability/CardAbility.js
- server/game/core/attack/Attack.ts
- server/game/core/attack/AttackFlow.ts
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/gameSystems/AttackSystem.ts
- test/server/cardImplementations/01_SOR/2-1BSurgicalDroid.spec.js
- test/server/cardImplementations/01_SOR/AvengerHuntingStarDestroyer.spec.js
Need to add one more test once Leader Units are implemented
> Mostly implementing Avenger

- server/game/cards/01_SOR/leaders/SabineWrenGalvanizedRevolutionary.ts
- server/game/core/Game.js
- server/game/core/card/BaseCard.ts
- server/game/core/clocks/ChessClock.ts
- server/game/core/gameSteps/prompts/GameOverPrompt.js
- test/server/cards/01_SOR/leaders/SabineWrenGalvanizedRevolutionary.spec.js
- test/server/core/Game.spec.js
Also implemented Sabine leader
> Added the functionality of the game ending in a draw.

- server/game/cards/01_SOR/units/AdmiralAckbarBrilliantStrategist.ts
- test/server/cards/01_SOR/units/AdmiralAckbarBrilliantStrategist.spec.ts
- test/server/cards/01_SOR/units/AdmiralAckbarBrilliantStrategist.ts
SWUDB: https://swudb.com/card/sor/097/admiral-ackbar
> Add card Admiral Ackbar (SOR 097)

- server/game/cards/01_SOR/events/AttackPatternDelta.ts
- test/server/cards/01_SOR/events/AttackPatternDelta.spec.ts
SWUDB: https://swudb.com/card/SOR/106/attack-pattern-delta
> Implement card Attack Pattern Delta (SOR 106)

- server/game/cards/01_SOR/units/SabineWrenExplosivesArtist.ts
- server/game/core/Constants.ts
- server/game/gameSystems/AttackStepsSystem.ts
- test/server/cards/01_SOR/units/SabineWrenExplosivesArtist.spec.ts
Implemented sentinel overriding "can't be attacked" abilities.
Removed the unused EffectName.CannotBeAttacked in Constants.ts, as it overlaps with AbilityRestriction.BeAttacked, which is actually used.
> Finished the implementation of Sabine Wren, Explosives Artist 

- server/game/Interfaces.ts
- server/game/core/ability/AbilityLimit.ts
- server/game/core/ability/ActionAbility.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/ability/EventAbility.ts
- server/game/core/ability/KeywordHelpers.ts
- server/game/core/ability/TriggeredAbility.ts
- server/game/core/card/Card.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/ongoingEffect/effectImpl/GainAbility.ts
Converted CardAbility to TS and discovered a bug with gained action abilities, now fixed.
> Convert CardAbility to TS and fix bug

- server/game/cards/01_SOR/units/PiratedStarfighter.ts
- test/server/cards/01_SOR/units/PiratedStarfighter.spec.ts
Implementation for pirated starfighter including two tests
> Implement Pirated Starfighter

- server/game/cards/01_SOR/units/BlizzardAssaultAtat.ts
- server/game/cards/01_SOR/units/RukhThrawnsAssassin.ts
- server/game/cards/02_SHD/units/DoctorPershingExperimentingWithLife.ts
- server/game/cards/02_SHD/units/PhaseiiiDarkTrooper.ts
- server/game/core/Constants.ts
- server/game/core/attack/AttackFlow.ts
- server/game/costs/CostLibrary.ts
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/SelectCardSystem.ts
- test/scenarios/event/ReplacementEffect.spec.ts
- test/server/cards/02_SHD/units/DoctorPershingExperimentingWithLife.spec.ts
> Add Doctor Pershing implementation

- server/game/core/gameSteps/phases/SetupPhase.ts
- server/game/core/gameSteps/prompts/MulliganPrompt.ts
- test/server/core/gameSteps/phases/SetupPhase.spec.ts
- Added mulligan simultaneus for both players.
- Added tests to the SetupPhase to support MulliganPrompt.ts
> #Setup-Phase Mulligan

- server/game/cards/02_SHD/events/MaKlounkee.ts
- test/server/cards/02_SHD/events/MaKlounkee.spec.ts
> Implement Ma Klounkee

- server/game/cards/01_SOR/units/SpecForceSoldier.ts
- server/game/core/GameObject.ts
- server/game/core/ability/KeywordInstance.ts
- server/game/core/card/Card.ts
- server/game/core/ongoingEffect/IOngoingCardEffect.ts
- server/game/core/ongoingEffect/effectImpl/LoseKeyword.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/scenarios/constantEffectInteractions/losingAndGainingKeywords.spec.ts
- test/server/cards/01_SOR/units/SpecForceSoldier.spec.ts
Implemented keyword losing effects including some tests to cover complex situations involving when a keyword should and shouldn't be regained.
Implemented SpecForce Soldier.
> Keyword losing effects

- server/game/cards/01_SOR/units/K2SOCassiansCounterpart.ts
- test/server/cards/01_SOR/units/K2SOCassiansCounterpart.spec.ts
> Add K2SO implementation

- server/game/cards/01_SOR/upgrades/SnapshotReflexes.ts
- test/server/cards/01_SOR/upgrades/SnapshotReflexes.spec.ts
> Snapshot Reflexes implementation

- server/game/cards/01_SOR/events/ForcedSurrender.ts
- server/game/core/Constants.ts
- server/game/gameSystems/DiscardCardsFromHand.ts
- server/game/gameSystems/DrawSystem.ts
- server/game/stateWatchers/DamageDealtThisPhaseWatcher.ts
- server/game/stateWatchers/StateWatcherLibrary.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/01_SOR/events/ForcedSurrender.spec.ts
> Add Forced Surrender implementation

- server/game/cards/01_SOR/units/LandoCalrissianResponsibleBusinessman.ts
- server/game/core/Player.js
- server/game/gameSystems/MoveCardSystem.ts
- test/server/cards/01_SOR/units/LandoCalrissianResponsibleBusinessman.spec.ts
> Add Lando Calrissian implementation

- .github/workflows/pullrequest.yml
- bin/fetchdata.js
Update the cache as a quotation mark got changed in the Qi'ra leader name. Also removed TWI from the script for now since it's not supposed to be started yet.
> Update cache name and remove TWI

- server/game/cards/01_SOR/units/FrontlineShuttle.ts
- test/server/cards/01_SOR/units/FrontlineShuttle.spec.ts
> feat: implement frontline shuttle

- server/game/cards/02_SHD/leaders/FinnThisIsARescue.ts
- test/server/cards/02_SHD/leaders/FinnThisIsARescue.spec.ts
This was more complicated than I anticipated. The tests might be a little verbose, happy to distill it down to fewer actions per test if that makes sense.
> Add 02_SHD leader Finn

- server/game/core/Player.js
- server/game/core/zone/DeckZone.ts
Small fix for reporting a Zone Summary as well as deck shuffling fix.
> fix zone summary method

- server/game/cards/02_SHD/events/Evacuate.ts
- test/server/cards/02_SHD/events/Evacuate.spec.ts
Added evacuate logic and unit test.  Made sure upgrades get defeated/discarded while units return to hand
> SHD# 233 Evacuate implementation

- server/game/cards/02_SHD/upgrades/BountyHuntersQuarry.ts
- test/server/cards/02_SHD/upgrades/BountyHuntersQuarry.spec.ts
- test/server/cards/02_SHD/upgrades/EnticingReward.spec.ts
> feat: implement bounty hunters quarry

- server/game/cards/02_SHD/units/KintanIntimidator.ts
- test/server/cards/02_SHD/units/KintanIntimidator.spec.ts
> SHD# Kintan Intimidator card

- server/game/cards/02_SHD/units/GreySquadronYWing.ts
- test/server/cards/02_SHD/units/GreySquadronYWing.spec.ts
> feat: implement grey squadron y wing

- server/game/cards/01_SOR/leaders/CassianAndorDedicatedToTheRebellion.ts
- server/game/stateWatchers/DamageDealtThisPhaseWatcher.ts
- test/server/cards/01_SOR/leaders/CassianAndorDedicatedToTheRebellion.spec.ts
Added cassian andor leader card / unit.  Had to make a small update to the damage dealt tracker to keep track of amount as well
> SOR #13 Cassian Andor Leader

- server/game/cards/02_SHD/units/RecklessGunslinger.ts
- test/server/cards/02_SHD/units/RecklessGunslinger.spec.ts
First PR, reckless gunslinger implementation from SHD. 
Hopefully everything looks correct.
> SHD #160 Reckless Gunslinger Unit Implementation

- server/game/actions/PlayUnitAction.ts
- server/game/cards/02_SHD/leaders/HanSoloWorthTheRisk.ts
- server/game/cards/02_SHD/units/ArquitensAssaultCruiser.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PutIntoPlaySystem.ts
- test/server/cards/02_SHD/leaders/FennecShandHonoringTheDeal.spec.ts
- test/server/cards/02_SHD/leaders/HanSoloWorthTheRisk.spec.ts
> han solo 2

- server/game/cards/01_SOR/events/Karabast.ts
- server/game/cards/01_SOR/events/MaximumFirePower.ts
- server/game/cards/01_SOR/events/StrikeTrue.ts
- server/game/cards/02_SHD/events/LetTheWookieeWin.ts
- server/game/cards/02_SHD/units/TarffulKashyyykChieftain.ts
- server/game/gameSystems/DamageSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/02_SHD/events/LetTheWookieeWin.spec.ts
- test/server/cards/02_SHD/units/TarffulKashyyykChieftain.spec.ts
| Tarfful | Let The Wookiee Win |
| ------ | -------- |
| ![image](https://github.com/user-attachments/assets/9c89fd2c-9ec2-4528-8ce4-90c7a01e5324) | ![image](https://github.com/user-attachments/assets/5119bf85-18e9-4c91-a3a1-cd8c06359d78) |
> Add Tarfful and Let The Wookiee Win implementation

- server/game/cards/01_SOR/events/Vigilance.ts
- server/game/core/Constants.ts
- server/game/gameSystems/ChooseModalEffectsSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PlayModalCardSystem.ts
- test/server/cards/01_SOR/events/Vigilance.spec.ts
- Implemented playingModalCards system
- Added Vigilance card and tests.
> Che bato/modal cards

- server/game/cards/02_SHD/units/CassianAndorRebellionsAreBuiltOnHope.ts
- test/server/cards/02_SHD/units/CassianAndorRebellionsAreBuiltOnHope.spec.ts
A test file is also included with the implementation. This is my first pull request to this repository, so I have chosen the Cassian Andor Unit Card.
> #148 Cassian Andor, Rebellions Are Built On Hope Unit Implementation

- .github/workflows/pullrequest.yml
- .github/workflows/update-cache.yml
- bin/fetchdata.js
- server/game/cards/01_SOR/units/ChimaeraFlagshipOfTheSeventhFleet.ts
- server/game/core/Game.js
- test/helpers/GameFlowWrapper.js
- test/helpers/IntegrationHelper.d.ts
- test/helpers/IntegrationHelper.js
- test/server/cards/01_SOR/units/ChimaeraFlagshipOfTheSeventhFleet.spec.ts
Added Chimaera and a way to create a dropdown with all playable card titles for this and other similar effects such as Regional Governor
> Chimaera and card titles dropdown

- server/game/cards/01_SOR/units/LothalInsurgent.ts
- server/game/core/utils/Helpers.ts
- server/game/gameSystems/DiscardCardsFromHand.ts
- server/game/gameSystems/DiscardCardsFromHandSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/01_SOR/units/LothalInsurgent.spec.ts
> Add Lothal Insurgent and random discard option

- server/game/cards/02_SHD/units/StreetGangRecruiter.ts
- test/server/cards/02_SHD/units/StreetGangRecruiter.spec.ts
> Implementing Street Gang Recruiter

- server/game/cards/02_SHD/units/LadyProximaWhiteWormMatriarch.ts
- test/server/cards/02_SHD/units/LadyProximaWhiteWormMatriarch.spec.ts
> Implementing Lady Proxima, White Worm Matriarch

- server/game/core/card/Card.ts
- server/gamenode/defaultGame.js
A few small additions to support card images
> support card images

- server/game/cards/01_SOR/units/FightersForFreedom.ts
- test/server/cards/01_SOR/units/FightersForFreedom.spec.ts
> SOR #143 Fighters for Freedom

- server/game/core/gameSteps/ActionWindow.js
- test/server/cards/01_SOR/units/GideonHaskRuthlessLoyalist.spec.ts
add baseZone cards to list of cards looked at for actions
> add basezone to action window

- server/game/cards/02_SHD/units/OmegaPartOfTheSquad.ts
- test/server/cards/02_SHD/units/OmegaPartOfTheSquad.spec.ts
Bugfix to omega not checking the trait of the card being played
> Omega bugfix for card trait

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Added the ability to create joinable game lobbies.
- Added disconnect handling.
- Added clean up method for lobbies.
> Che bato/game lobby

- bin/fetchdata.js
Creates a map of SetCode to card id to be used for mapping swudb deck lists to card data.
> create set code map

- server/game/cards/01_SOR/units/BenduTheOneInTheMiddle.ts
- server/game/cards/02_SHD/leaders/JabbaTheHuttHisHighExaltedness.ts
- server/game/core/ongoingEffect/OngoingEffect.ts
- test/server/cards/02_SHD/leaders/JabbaTheHuttHisHighExaltedness.spec.ts
> Jabba The Hutt leader SHD

- server/game/cards/02_SHD/events/ChooseSides.ts
- test/server/cards/02_SHD/events/ChooseSides.spec.ts
> Add Choose Sides implementation

- package-lock.json
- server/game/cards/02_SHD/units/ValiantAssaultShip.ts
- test/server/cards/02_SHD/units/ValiantAssaultShip.spec.ts
> Implementing Valiant Assault Ship

- server/game/cards/03_TWI/events/GuardingTheWay.ts
- test/server/cards/03_TWI/events/GuardingTheWay.spec.ts
I didn't see in the tests for a way to check for Sentinel other than just attacking so that is the direction I went.
> Implementing Guarding the Way

- server/game/cards/03_TWI/units/332ndStalwart.ts
- server/game/cards/03_TWI/units/RepublicCommando.ts
- test/server/cards/03_TWI/units/RepublicCommando.spec.ts
- test/server/cards/03_TWI/units/_332ndStalwart.spec.ts
> Implementing 332nd Stalwart and Republic Commando

- server/game/cards/03_TWI/units/PadawanStarFighter.ts
- test/server/cards/03_TWI/units/PadawanStarFighter.spec.ts
Adding my first card.
There is no upgrade with Force trait (as far as I know). But I added a text with an upgrade.
> add padawan starfighter

- server/game/cards/02_SHD/units/BoKatanKryzeFightingForMandalore.ts
- test/server/cards/02_SHD/units/BoKatanKryzeFightingForMandalore.spec.ts
Implements the logic for BokatanKyrzeFightingForMandalore.
Unit tests include cases for when each player has correct damage on base to trigger when defeated response. 
Please review and provide feedback. First implementation for Karabast!
> BokatanKyrzeFightingForMandalore (SHD) card implementation 

- server/game/cards/03_TWI/units/PloKoonKohtoyah.ts
- test/server/cards/03_TWI/units/PloKoonKohtoyah.spec.ts
> add plo koon kohtoyah

- server/game/cards/03_TWI/units/SavageOpressMonster.ts
- test/server/cards/03_TWI/units/SavageOpressMonster.spec.ts
> add savage opress monster

- server/game/cards/03_TWI/units/RoyalGuardAttache.ts
- test/server/cards/03_TWI/units/RoyalGuardAttache.spec.ts
> [+] RoyalGuardAttache: Card Integration

- server/game/cards/03_TWI/units/HevyStaunchMartyr.ts
- test/server/cards/03_TWI/units/HevyStaunchMartyr.spec.ts
Adding [Hevy](https://swudb.com/card/TWI/164/hevy).
I lost time understanding that I should not use targetResolver. I am still learning :)
> TWI hevy staunch martyr

- server/game/cards/03_TWI/units/VanguardDroidBomber.ts
- test/server/cards/03_TWI/units/VanguardDroidBomber.spec.ts
[Vanguard droid bomber](https://swudb.com/card/twi/160/vanguard-droid-bomber)
> add vanguard-droid-bomber

- server/game/cards/03_TWI/upgrades/AhsokasPadawanLightsaber.ts
- test/server/cards/03_TWI/upgrades/AhsokasPadawanLightsaber.spec.ts
> Implementing Ahsoka's Padawan Lightsaber

- server/game/cards/03_TWI/units/OOMSeriesOfficer.ts
- test/server/cards/03_TWI/units/OOMSeriesOfficer.spec.ts
> [+] OOM-Series Officer: Card Integration

- server/game/cards/01_SOR/units/C-3POProtocolDroid.ts
- server/game/cards/01_SOR/units/LieutenantChildsenDeathStarPrisonWarden.ts
- server/game/cards/01_SOR/units/ReinforcementWalker.ts
- server/game/cards/02_SHD/units/L3-37DroidRevolutionary.ts
- server/game/core/ability/ActionAbility.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/ability/CardAbilityStep.js
- server/game/core/ability/PlayerOrCardAbility.js
- server/game/core/gameSteps/AbilityResolver.js
- server/game/core/gameSteps/abilityWindow/TriggeredAbilityWindow.ts
- test/helpers/IntegrationHelper.js
- test/server/cards/01_SOR/units/ReinforcementWalker.spec.ts
- test/server/cards/02_SHD/units/L3-37DroidRevolutionary.spec.ts
> L3-37 droid revolutionary

- server/game/cards/03_TWI/events/CaughtInTheCrossfire.ts
- server/game/cards/03_TWI/events/MercilessContest.ts
- test/server/cards/03_TWI/events/CaughtInTheCrossfire.spec.ts
- test/server/cards/03_TWI/events/MercilessContest.spec.ts
| Merciless Contest | Caught In The Crossfire |
| - | - |
| ![image](https://github.com/user-attachments/assets/c9f097af-9514-4085-858b-defe14820a64) | ![image](https://github.com/user-attachments/assets/914ba8ad-cb6c-459f-b497-a243b2ce37f4) |
> Add Merciless Contest and Caught In The Crossfire

- server/game/cards/03_TWI/units/InfantryOfThe212th.ts
- test/server/cards/03_TWI/units/InfantryOfThe212th.spec.ts
> [+] InfantryOfThe212th: Card Implementation

- server/game/cards/03_TWI/events/SwordAndShieldManeuver.ts
- test/server/cards/03_TWI/events/SwordAndShieldManeuver.spec.ts
[Sword and Shield Maneuver](https://swudb.com/card/TWI/250/sword-and-shield-maneuver)
> add Sword and Shield Maneuver

- server/game/cards/02_SHD/units/FinalizerMightOfTheFirstOrder.ts
- server/game/core/utils/EnumHelpers.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/02_SHD/units/FinalizerMightOfTheFirstOrder.spec.ts
> Add Finalizer

- server/game/cards/03_TWI/units/ShaakTiUnityWinsWars.ts
- test/server/cards/03_TWI/units/ShaakTiUnityWinsWars.spec.ts
[Shaak Ti](https://swudb.com/card/TWI/094/shaak-ti)
> add shaak ti

- server/game/cards/03_TWI/upgrades/CloneCohort.ts
- test/server/cards/03_TWI/upgrades/CloneCohort.spec.ts
[Clone Cohort](https://www.swudb.com/card/TWI/169/clone-cohort)
> add Clone Cohort

- server/gamenode/Lobby.ts
- Fixes the lobby crashing when player 2 joins.
> #lobby-crash-fix

- server/game/cards/01_SOR/upgrades/Traitorous.ts
- server/game/cards/02_SHD/units/SurvivorsGauntlet.ts
- server/game/cards/Index.ts
- server/game/core/Constants.ts
- server/game/core/gameSystem/CardTargetSystem.ts
- server/game/gameSystems/AttachUpgradeSystem.ts
- test/server/cards/01_SOR/upgrades/Traitorous.spec.ts
- test/server/cards/02_SHD/units/SurvivorsGauntlet.spec.ts
| Traitorous | Survivors Gauntlet |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c92f375f-0e1e-4035-ab2c-c0adfe7db223) | ![image](https://github.com/user-attachments/assets/d469a1e5-6386-446c-b24d-38b9d53ebdaa) |
> Add Traitorous and Survivors Gauntlet

- server/game/cards/03_TWI/events/PyrrhicAssault.ts
- test/server/cards/03_TWI/events/PyrrhicAssault.spec.ts
> Implementing Pyrrhic Assault

- test/helpers/DeckBuilder.js
- test/helpers/PlayerInteractionWrapper.js
- test/helpers/Util.js
- test/server/cards/01_SOR/events/ChangeOfHeart.spec.ts
- test/server/cards/01_SOR/tokens/TokenUnits.spec.ts
- test/server/cards/01_SOR/units/BrightHopeTheLastTransport.spec.ts
- test/server/cards/02_SHD/events/ANewAdventure.spec.ts
- test/server/core/card/TakeControl.spec.ts
Added support for token units in test spec. Also cleaned up the owner vs controller thing a bit, renamed the property for units to be `owner` instead of `ownerAndController` since the former is more correct. Did some general cleanup as well.
> Test spec improvements

- server/game/cards/03_TWI/events/InDefenseOfKamino.ts
- test/server/cards/03_TWI/events/InDefenseOfKamino.spec.ts
> Implementing In Defense of Kamino

- scripts/run-server.js
- server/game/core/gameSteps/ActionWindow.js
- server/gamenode/Lobby.ts
- server/logger.ts
During local dev testing, exceptions were not being emitted to the console
> Enable logging of exceptions while in game

- server/game/cards/03_TWI/upgrades/HoldoutBlaster.ts
- test/server/cards/03_TWI/upgrades/HoldoutBlaster.spec.js
[Holdout Blaster](https://swudb.com/card/twi/256/hold-out-blaster)
> add holdout blaster

- server/game/core/card/Card.ts
- server/game/core/card/UpgradeCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Server support for GameCard tokens such as shield, upgrades, experience, sentinel, power and hp
> Che bato/game card icons

- server/game/cards/03_TWI/units/AsajjVentressCountDookusAssassin.ts
- test/server/cards/03_TWI/units/AsajjVentressCountDookusAssassin.spec.ts
[Asajj Ventress](https://swudb.com/card/twi/134/asajj-ventress)
> add asajj ventress count dooku assassin

- server/game/core/card/baseClasses/InPlayCard.ts
- test/server/cards/03_TWI/units/EncouragingLeadership.spec.ts
Fixed a bug where lasting effects applied to a card would continue to be applied even if the card left and re-entered play.
> Fix lasting effect falloff bug

- server/game/cards/03_TWI/events/PrisonerOfWar.ts
- test/server/cards/03_TWI/events/PrisonerOfWar.spec.ts
> Implementing Prisoner of War

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Support for Quickplay.
- Added matchmaking queue.
- Changed that the lobby doesn't show if a user disconnects and a game already exists.
> #QuickPlay

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Added support for playableCardTitles to lobbies.
> #PlayableCardTitles

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Added private lobbies to gameServer.
- Made it possible to join via links.
- Made it possible for players to create private lobbies without logging in.
> #PrivateLobbies

- server/gamenode/GameServer.ts
> Add health check API

- server/game/cards/03_TWI/events/CornerThePrey.ts
- test/server/cards/03_TWI/events/CornerThePrey.spec.ts
[Corner the prey](https://swudb.com/card/TWI/139/corner-the-prey)
> Corner the prey

- server/game/core/Constants.ts
- server/game/core/Game.js
- server/game/core/GamePipeline.ts
- server/game/core/PlayerPromptState.ts
- server/game/core/gameSteps/BaseStep.ts
- server/game/core/gameSteps/BaseStepWithPipeline.ts
- server/game/core/gameSteps/IStep.ts
- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DisplayCardPrompt.ts
- server/game/core/gameSteps/prompts/DisplayCardsWithButtonsPrompt.ts
- server/game/core/gameSteps/prompts/UiPrompt.ts
- server/game/gameSystems/DistributeAmongTargetsSystem.ts
- server/game/gameSystems/DistributeDamageSystem.ts
- server/game/gameSystems/DistributeExperienceSystem.ts
- server/game/gameSystems/DistributeHealingSystem.ts
- server/game/gameSystems/LookMoveDeckCardsTopOrBottomSystem.ts
- test/helpers/CustomMatchers.js
- test/helpers/IntegrationHelper.d.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/01_SOR/units/InfernoFourUnforgetting.spec.ts
- test/server/cards/01_SOR/units/R2D2IgnoringProtocol.spec.ts
Initial pieces for the new prompt type that will be used for Vader / U-Wing. Added the IDisplayCard interface and the DisplayCardPrompt which passes a set of them.
Migrated the "move to top / bottom of deck" system to use the new prompt and updated the tests.
> Add DisplayCardsPrompt with implementation for move to top / bottom of deck

- server/game/cards/03_TWI/upgrades/SquadSupport.ts
- test/server/cards/03_TWI/upgrades/SquadSupport.spec.ts
[Squad Support](https://swudb.com/card/twi/122/squad-support)
> add squad support

- server/game/cards/03_TWI/units/HeavyPersuaderTank.ts
- test/server/cards/03_TWI/units/HeavyPersuaderTank.spec.ts
> Implement Heavy Persuader Tank (TWI 167)

- server/game/cards/02_SHD/units/PoeDameronQuickToImprovise.ts
- test/server/cards/01_SOR/units/PoeDameronQuickToImprovise.spec.ts
[Poe Dameron](https://swudb.com/card/SHD/153/poe-dameron)
> Poe Dameron

- server/game/cards/01_SOR/events/UWingReinforcement.ts
- server/game/core/Player.js
- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DisplayCardsForSelectionPrompt.ts
- server/game/core/zone/DeckZone.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PlayCardSystem.ts
- server/game/gameSystems/PlayMultipleCardsFromDeckSystem.ts
- server/game/gameSystems/SearchDeckSystem.ts
- test/helpers/CustomMatchers.js
- test/helpers/IntegrationHelper.d.ts
- test/helpers/PlayerInteractionWrapper.js
- test/helpers/Util.js
- test/server/cards/01_SOR/events/UWingReinforcement.spec.ts
- test/server/cards/02_SHD/events/BountyPosting.spec.ts
- test/server/cards/02_SHD/events/ThisIsTheWay.spec.ts
- test/server/cards/02_SHD/upgrades/EnticingReward.spec.ts
Added U-Wing Reinforcements and expanded the display cards prompt to accommodate a "multi-select condition" indicating which normally valid cards might become unselectable based on the existing selection set.
> Add U-Wing and new prompt support

- server/game/cards/03_TWI/upgrades/RogerRoger.ts
- test/server/cards/03_TWI/upgrades/RogerRoger.spec.ts
> Implement Roger Roger (TWI #69)

- server/game/cards/02_SHD/units/KuiilIHaveSpoken.ts
- test/server/cards/02_SHD/units/KuiilIHaveSpoken.spec.ts
> Implementing Kuiil, I Have Spoken

- server/game/cards/03_TWI/events/UnlimitedPower.ts
- server/game/cards/03_TWI/units/MagnaguardWingLeader.ts
- test/server/cards/03_TWI/events/UnlimitedPower.spec.ts
- test/server/cards/03_TWI/units/MagnaguardWingLeader.spec.ts
| Unlimited Power | MagnaGuard Wing Leader |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/ea80f1e5-b205-4ffd-9c54-2398d354e417) | ![image](https://github.com/user-attachments/assets/de88aaa5-bb65-4480-9219-9e2b5b2a1c71) |
> Add Unlimited Power and MagnaGuard Wing Leader

- server/game/cards/02_SHD/events/TripleDarkRaid.ts
- test/server/cards/02_SHD/events/TripleDarkRaid.spec.ts
> Implement Triple Dark Raid

- server/gamenode/GameServer.ts
Simplify server contructor and set cors rules
> Server config 1242025

- server/game/cards/02_SHD/units/StolenLandspeeder.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/ability/TriggeredAbility.ts
- test/scenarios/timingWindows/DefeatTiming.spec.ts
- test/server/cards/02_SHD/units/StolenLandspeeder.spec.ts
> Add Stolen Landspeeder implementation

- server/gamenode/Lobby.ts
Quick! Merge this before anyone sees!
> I am in fact a doofus

- server/game/core/PlayerPromptState.ts
- server/game/core/card/Card.ts
- server/game/core/gameSteps/ActionWindow.js
- server/game/core/gameSteps/prompts/DistributeAmongTargetsPrompt.ts
- server/game/core/gameSteps/prompts/DropdownListPrompt.ts
- server/game/core/gameSteps/prompts/GameOverPrompt.js
- server/game/core/gameSteps/prompts/HandlerMenuPrompt.js
- server/game/core/gameSteps/prompts/MenuPrompt.js
- server/game/core/gameSteps/prompts/ResourcePrompt.ts
- server/game/core/gameSteps/prompts/SelectCardPrompt.ts
- server/game/core/gameSteps/prompts/UiPrompt.ts
- server/game/core/gameSteps/prompts/VariableResourcePrompt.ts
Cleaning up a few open issues related to prompts:
- Resource selection prompts wouldn't let you unselect cards once the maximum amount of resources were selected
- Cards were remaining in a highlighted / selectable state even after a prompt resolved
> Prompt fixes

- server/game/cards/02_SHD/upgrades/SecondChance.ts
- test/server/cards/02_SHD/upgrades/SecondChance.spec.ts
> Implement Second Chance (SHD 053)

- server/game/core/card/BaseCard.ts
- server/game/core/card/Card.ts
- server/game/core/card/LeaderUnitCard.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
The FE needs to know if a card's epic action is spent so it can render an icon. Added that and cleaned up some various method signatures.
> Add epicActionSpent property to card summary

- server/game/cards/01_SOR/units/GamorreanGuards.ts
- server/game/cards/02_SHD/units/GamorreanRetainer.ts
- test/server/cards/02_SHD/units/GamorreanRetainer.spec.ts
- test/server/core/card/TakeControl.spec.ts
> gamorrean retainer

- server/game/cards/03_TWI/units/SanHillChairmanOfTheBankingClan.ts
- test/server/cards/03_TWI/units/SanHillChairmanOfTheBankingClan.spec.ts
> Implementing San Hill, Chairman of the Banking Clan

- server/game/cards/03_TWI/bases/DroidManufactory.ts
- server/game/cards/03_TWI/bases/ShadowCollectiveCamp.ts
- test/server/cards/03_TWI/bases/ShadowCollectiveCamp.spec.ts
> Shadow Collective Camp

- server/game/cards/02_SHD/units/AdelphiPatrolWing.ts
- server/game/cards/02_SHD/units/ChewbaccaPykesbane.ts
- test/server/cards/02_SHD/units/AdelphiPatrolWing.spec.ts
- test/server/cards/02_SHD/units/ChewbaccaPykesbane.spec.ts
- test/server/core/abilities/keyword/Smuggle.spec.ts
> Shadow cards

- server/game/cards/02_SHD/leaders/GarSaxonViceroyofMandalore.ts
- test/server/cards/02_SHD/leaders/GarSaxonViceroyOfMandalore.spec.ts
> Implement Gar Saxon, Viceroy of Mandalore

- server/game/cards/02_SHD/leaders/LandoCalrissianWithImpeccableTaste.ts
- test/server/cards/02_SHD/leaders/LandoCalrissianWithImpeccableTaste.spec.ts
Looks like order of defeating resource and hot shot attack is correct based off of this:
> Implement Lando Calrissian, With Impeccable Taste

- server/game/cards/03_TWI/units/JarJarBinksFoolishGungan.ts
- test/server/cards/03_TWI/units/JarJarBinksFoolishGungan.spec.ts
> Implementing Jar Jar Binks

- server/Settings.ts
- server/game/core/Player.js
- server/gamenode/defaultGame.js
- test/helpers/GameFlowWrapper.js
- test/helpers/GameStateSetup.js
- test/helpers/IntegrationHelper.js
- test/helpers/PlayerInteractionWrapper.js
Sets autoSingleTarget to be a user setting. The default for this is set to be true for default users, but can be overridden in testing setup. This is set to false for jasmine tests.
> Auto single target as setting

- server/game/cards/04_JTL/tokens/TieFighter.ts
- server/game/cards/04_JTL/tokens/XWing.ts
- server/game/cards/04_JTL/units/GeneralDravenDoingWhatMustBeDone.ts
- server/game/cards/04_JTL/units/QuasarTieCarrier.ts
- server/game/core/Constants.ts
- server/game/gameSystems/CreateTieFighterSystem.ts
- server/game/gameSystems/CreateXWingSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/helpers/DeckBuilder.js
- test/server/cards/04_JTL/units/GeneralDravenDoingWhatMustBeDone.spec.ts
- test/server/cards/04_JTL/units/QuasarTieCarrier.spec.ts
> xwing & tie fighter

- server/game/cards/03_TWI/events/GuerillaInsurgency.ts
- test/server/cards/03_TWI/events/GuerillaInsurgency.spec.ts
> Implementing Guerilla Insurgency

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Refactored the way we send data to the backend. Currently we want to send both the reconstructed deck and the swuDB deck. So me and Veld can simultaneously work on the implementation. The user in the lobby also has swuDeck data.
> #DeckDataRefactor

- server/game/cards/02_SHD/events/RelentlessPursuit.ts
- server/game/cards/02_SHD/events/RuleWithRespect.ts
- server/game/cards/02_SHD/events/TakeCaptive.ts
- server/game/cards/02_SHD/events/UnexpectedEscape.ts
- server/game/cards/02_SHD/leaders/JabbaTheHuttHisHighExaltedness.ts
- server/game/cards/02_SHD/units/DiscerningVeteran.ts
- server/game/cards/02_SHD/units/EphantMonHeadOfSecurity.ts
- server/game/cards/02_SHD/units/FinalizerMightOfTheFirstOrder.ts
- server/game/cards/02_SHD/units/L3-37DroidRevolutionary.ts
- server/game/cards/02_SHD/upgrades/LegalAuthority.ts
- server/game/cards/02_SHD/upgrades/TheMandaloriansRifle.ts
- server/game/cards/03_TWI/events/PrisonerOfWar.ts
Capture is now working in the FE, removing the unimplemented marker from those cards
> Remove unimplemented flag from capture cards

- server/game/cards/03_TWI/leaders/AhsokaTanoSnips.ts
- server/game/cards/03_TWI/leaders/PadmeAmidalaServingTheRepublic.ts
- server/game/core/card/Card.ts
- server/game/core/card/LeaderUnitCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- test/server/cards/03_TWI/leaders/AhsokaTanoSnips.spec.ts
- test/server/cards/03_TWI/leaders/PadmeAmidalaServingTheRepublic.spec.ts
| Leader side | Leader unit side |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/37d515ff-1c4a-4b55-aee7-5fcd1115518a) | ![image](https://github.com/user-attachments/assets/d66e8ae4-2640-41bf-8b34-93c90905c208) |
| ![image](https://github.com/user-attachments/assets/180bbab1-7fbd-4f98-b858-0bf6638b49d3) | ![image](https://github.com/user-attachments/assets/e9fd24a2-4924-4655-b36c-74e3d3be0ab1) |
> Add Ashoka and Padme leaders

- server/game/actions/PlayEventAction.ts
- server/game/actions/PlayUnitAction.ts
- server/game/actions/PlayUpgradeAction.ts
- server/game/core/ability/PlayCardAction.ts
- test/server/core/abilities/keyword/Smuggle.spec.ts
Fixed an issue where Smuggling while the deck is empty caused an error.
> Smuggle bug fix

- server/game/cards/04_JTL/units/BlackSquadronScoutWing.ts
- test/server/cards/04_JTL/units/BlackSquadronScoutWing.spec.ts
> Implementing Black Squadron Scout Wing

- server/game/cards/04_JTL/events/NoDisintegrations.ts
- server/game/cards/04_JTL/units/HoundsToothReliableAndDeadly.ts
- test/server/cards/04_JTL/events/NoDisintegrations.spec.ts
- test/server/cards/04_JTL/units/HoundsToothReliableAndDeadly.spec.ts
> No Disintegrations and Hound's Tooth

- server/game/core/Game.js
- server/game/core/gameSteps/PromptInterfaces.ts
- server/game/core/gameSteps/prompts/DistributeAmongTargetsPrompt.ts
- server/game/gameSystems/DistributeAmongTargetsSystem.ts
- test/helpers/PlayerInteractionWrapper.js
Transfor card uuids to the card objects to be consumed by prompt
> transform data from FE for stateful prompt

- server/game/TargetInterfaces.ts
- server/game/cards/02_SHD/events/EndlessLegions.ts
- server/game/core/ability/PlayCardAction.ts
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/gameSystems/PutIntoPlaySystem.ts
- test/server/cards/02_SHD/events/EndlessLegions.spec.ts
> Add Endless Legions implementation

- server/game/cards/02_SHD/units/RicketyQuadjumper.ts
- server/game/cards/03_TWI/upgrades/Foresight.ts
- test/server/cards/02_SHD/units/RicketyQuadjumper.spec.ts
- test/server/cards/03_TWI/upgrades/Foresight.spec.ts
> Foresight & Rickety Quad jumper- prompt

- server/game/cards/01_SOR/units/C-3POProtocolDroid.ts
- test/server/cards/01_SOR/units/C-3POProtocolDroid.spec.ts
| Controller (correct guess) | Controller (incorrect guess) | Opponent (card reveal) |
| :---: | :---: | :---: |
| <img src="https://github.com/user-attachments/assets/931c7f35-5ac8-4b27-951a-8f35e210d5c5" /> | <img src="https://github.com/user-attachments/assets/6a75e15c-f133-447e-b2b3-ab67d7964ab4" /> | <img src="https://github.com/user-attachments/assets/e40b9c13-4260-440f-9e93-908271c799a4" /> |
> Update C-3PO display prompts

- server/game/core/gameSteps/prompts/HandlerMenuMultipleSelectionPrompt.js
Adds selected state to buttons for prompts requiring multiple button selections i.e Yoda, Old Master
> Add multiselect button state

- server/game/cards/01_SOR/events/ForACauseIBelieveIn.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/01_SOR/events/ForACauseIBelieveIn.spec.ts
This card uses the new display prompt:
> Implement For a Cause I Believe In

- server/game/cards/01_SOR/units/BlackOneScourgeOfStarkillerBase.ts
- server/game/cards/01_SOR/units/GreedoSlowOnTheDraw.ts
- server/game/cards/01_SOR/units/K2SOCassiansCounterpart.ts
- server/game/cards/01_SOR/units/RuthlessRaider.ts
- server/game/cards/02_SHD/units/BoKatanKryzeFightingForMandalore.ts
- server/game/cards/03_TWI/units/FavorableDelegate.ts
- server/game/cards/03_TWI/units/HevyStaunchMartyr.ts
- server/game/cards/03_TWI/units/SenatorialCorvette.ts
- server/game/cards/04_JTL/events/NoGloryOnlyResults.ts
- server/game/cards/04_JTL/units/ProfundityWeFight.ts
- test/server/cards/04_JTL/events/NoGloryOnlyResults.spec.ts
- test/server/cards/04_JTL/units/ProfundityWeFight.spec.ts
| No Glory, No Results | Profundity |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5ea1150f-a463-4c6a-8571-ac198643e562) | ![image](https://github.com/user-attachments/assets/b2b6069a-f734-4bfd-843f-547767060628) |
> Add No Glory, No Results and Profundity implementation

- server/game/cards/02_SHD/events/FinalShowdown.ts
- server/game/core/Constants.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/LoseGameSystem.ts
- test/helpers/GameStateBuilder.js
- test/server/cards/02_SHD/events/FinalShowdown.spec.ts
> Add Final Showdown implementation

- server/AnonymousSpectator.ts
- server/Settings.ts
- server/Spectator.ts
- server/game/core/Game.js
- server/game/core/GameInterfaces.ts
- server/game/core/Player.js
- server/game/core/chat/GameChat.ts
- server/game/costs/PlayCardResourceCost.ts
- server/game/gameSystems/SearchDeckSystem.ts
- server/game/gameSystems/SimultaneousSystem.ts
- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- test/helpers/GameFlowWrapper.js
> Improve TS interfaces for Game and Player

- server/gamenode/GameServer.ts
> #BugFixForLobby

- server/game/cards/03_TWI/events/ExecuteOrder66.ts
- test/server/cards/03_TWI/events/ExecuteOrder66.spec.ts
[Execute Order 66](https://swudb.com/card/TWI/239/execute-order-66)
> add Execute Order 66

- server/gamenode/Lobby.ts
Only run deck validation if we have a deck to run validation on when creating a lobby. Need this to support test games.
> handle null deck

- server/gamenode/GameServer.ts
Adding this just to custom lobbies for now since we don't have format in matchmaking yet and it's not available in the beta. 
Sets format for test games to Open.
> Add format option to custom lobbies

- server/game/cards/02_SHD/events/EndlessLegions.ts
- test/server/cards/02_SHD/events/EndlessLegions.spec.ts
> Update Endless Legions to use new display prompt

- server/game/cards/01_SOR/events/DontGetCocky.ts
- test/server/cards/01_SOR/events/DontGetCocky.spec.ts
> Update Don't Get Cocky to use the new display prompt

- server/gamenode/GameServer.ts
- server/utils/deck/DeckValidator.ts
- Final touches to the unimplemented Page.
> #UnimplementedPage

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
- Final touches to Ongoing games.
> #OngoingGames

- server/game/cards/02_SHD/events/EvidenceOfTheCrime.ts
- server/game/cards/02_SHD/units/PreVizslaPowerHungry.ts
- server/game/core/Constants.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PayCardPrintedCostSystem.ts
- test/server/cards/02_SHD/events/EvidenceOfTheCrime.spec.ts
- test/server/cards/02_SHD/units/PreVizslaPowerHungry.spec.ts
| Evidence of the Crime | Pre Vizsla |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/64b6b037-5bf5-4053-bcb8-9c122cc7ab75) | ![image](https://github.com/user-attachments/assets/a2bf3a5a-6f47-4033-a3bb-b3972f9560a6) |
> Add Evidence of the Crime and Pre Vizsla

- server/game/Interfaces.ts
- server/game/cards/02_SHD/units/DjBlatantThief.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/gameSystems/DelayedEffectSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/01_SOR/events/SneakAttack.spec.ts
- test/server/cards/02_SHD/events/TripleDarkRaid.spec.ts
Solves #630 
DJ will probably need some additional tests with EL still
> Fix delayed effects targeting cards after zone change

- server/gamenode/Lobby.ts
Added when an opponent leaves mid game the user left wins the game.
> Added when an opponent leaves mid game the user left wins the game.

- server/game/cards/03_TWI/units/R2D2FullofSolutions.ts
- test/server/cards/03_TWI/units/R2D2FullofSolutions.spec.ts
Added target controller as self, and a test to ensure players cannot target the other players hand.
> Fix and test for r2d2

- server/game/cards/03_TWI/upgrades/MaceWindusLightsaber.ts
- test/server/cards/03_TWI/upgrades/MaceWindusLightsaber.spec.ts
> Implementing Mace Windu's Lightsaber

- server/game/cards/04_JTL/units/TieBomber.ts
- test/server/cards/04_JTL/units/TieBomber.spec.ts
- test/server/cards/04_JTL/upgrades/DorsalTurret.spec.ts
> Implementing Tie Bomber

- server/game/cards/04_JTL/units/RedSquadronYWing.ts
- test/server/cards/04_JTL/units/RedSquadronYWing.spec.ts
> Implementing Red Squadron Y-Wing

- server/game/cards/04_JTL/units/LandingShuttle.ts
- test/server/cards/04_JTL/units/LandingShuttle.spec.ts
> Implementing Landing Shuttle

- server/game/cards/04_JTL/units/ResupplyCarrier.ts
- test/server/cards/04_JTL/units/ResupplyCarrier.spec.ts
> Implementing Resupply Carrier

- server/game/cards/04_JTL/units/SpecialForcesTIEFighter.ts
- test/server/cards/04_JTL/units/SpecialForcesTIEFighter.spec.ts
> Implementing Special Forces TIE Fighter

- server/game/cards/02_SHD/units/SurvivorsGauntlet.ts
- test/server/cards/01_SOR/units/GuardianOfTheWhills.spec.ts
- test/server/cards/01_SOR/units/HomeOneAllianceFlagship.spec.ts
- test/server/cards/02_SHD/units/SurvivorsGauntlet.spec.ts
Fixing: https://github.com/SWU-Karabast/forceteki/issues/725
> Fixing #725

- server/game/cards/04_JTL/units/SabinesMasterpieceCrazyColorful.ts
- server/game/core/Constants.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/SelectPlayerSystem.ts
- test/server/cards/04_JTL/units/SabinesMasterpieceCrazyColorful.spec.ts
> Sabine's Masterpiece Implementation

- server/gamenode/GameServer.ts
- server/gamenode/QueueHandler.ts
Fixes an issue where the requeue socket event would get registered multiple times causing the user to eventually get queued with themselves.
> fix requeuing issues

- server/game/cards/04_JTL/units/HeraSyndullaWeveLostEnough.ts
- server/game/cards/04_JTL/units/IdenVersioAdaptOrDie.ts
- server/game/cards/04_JTL/units/Ig88MurderousPhlutdroid.ts
- server/game/cards/04_JTL/units/PaigeTicoDroppingTheHammer.ts
- server/game/cards/04_JTL/units/WingmanVictorTwoMaulerMithel.ts
- server/game/core/Constants.ts
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/utils/Helpers.ts
- test/server/cards/04_JTL/units/HeraSyndullaWeveLostEnough.spec.ts
- test/server/cards/04_JTL/units/IdenVersioAdaptOrDie.spec.ts
- test/server/cards/04_JTL/units/Ig88MurderousPhlutdroid.spec.ts
- test/server/cards/04_JTL/units/PaigeTicoDroppingTheHammer.spec.ts
- test/server/cards/04_JTL/units/WingmanVictorTwoMaulerMithel.spec.ts
No support yet for situations where a card can move from being a pilot to a unit while still on the field
> Add basic piloting abilities

- server/game/cards/04_JTL/units/BobaFettFearedBountyHunter.ts
- server/game/cards/04_JTL/units/FriskVanguardLoudmouth.ts
- server/game/cards/04_JTL/units/WingmanVictorThreeBackstabber.ts
- test/server/cards/04_JTL/units/BobaFettFearedBountyHunter.spec.ts
- test/server/cards/04_JTL/units/FriskVanguardLoudmouth.spec.ts
- test/server/cards/04_JTL/units/WingmanVictorThreeBackstabber.spec.ts
| Boba Fett | Wingman Victor Three | Frisk |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/b64bc299-cd76-4b09-9b8a-a4188f40be50) | ![image](https://github.com/user-attachments/assets/eb07ea64-0520-4381-b3e8-8f4027fede09) | ![image](https://github.com/user-attachments/assets/6e5b2de0-83be-4e7f-8261-e9a2a5826e36) |
> Add Boba Fett, Wingman Victor Three and Frisk pilots

- server/game/core/Player.js
- server/game/costs/PlayCardResourceCost.ts
- server/game/gameSystems/PlayCardSystem.ts
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/02_SHD/upgrades/TheDarksaber.spec.ts
> Fix cost adjustment for upgrades

- server/gamenode/Lobby.ts
- server/utils/deck/DeckValidator.ts
- returned the value of minimumDeckSize and maximumSideboard from the deckvalidator and supplied it to the FE.
> #DeckAndSideboardMax

- server/game/cards/04_JTL/events/Diversion.ts
- server/game/cards/04_JTL/units/CloakedStarViper.ts
- server/game/cards/04_JTL/units/CrackshotVWing.ts
- server/game/cards/04_JTL/units/JarekYeagerCoordinatingWithTheResistance.ts
- server/game/cards/04_JTL/upgrades/GrimValor.ts
- server/game/cards/04_JTL/upgrades/SuperheavyIonCannon.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- test/server/cards/04_JTL/events/Diversion.spec.ts
- test/server/cards/04_JTL/units/CloakedStarViper.spec.ts
- test/server/cards/04_JTL/units/CrackshotVWing.spec.ts
- test/server/cards/04_JTL/units/JarekYeagerCoordinatingWithTheResistance.spec.ts
- test/server/cards/04_JTL/upgrades/GrimValor.spec.ts
- test/server/cards/04_JTL/upgrades/SuperheavyIonCannon.spec.ts
> Bunch of cards (set4-bunch 10)

- server/game/cards/04_JTL/events/AttackRun.ts
- server/game/cards/04_JTL/events/DedicatedWingmen.ts
- server/game/cards/04_JTL/events/EvasiveManeuver.ts
- server/game/cards/04_JTL/units/BunkerDefender.ts
- server/game/cards/04_JTL/units/CloneCombatSquadron.ts
- server/game/cards/04_JTL/units/DilapidatedSkiSpeeder.ts
- server/game/cards/04_JTL/units/IndependentSmuggler.ts
- server/game/cards/04_JTL/units/InsurgentSaboteurs.ts
- server/game/cards/04_JTL/units/SupportingEta2.ts
- server/game/cards/04_JTL/units/VeteranFleetOfficer.ts
- test/server/cards/04_JTL/events/AttackRun.spec.ts
- test/server/cards/04_JTL/events/DedicatedWingmen.spec.ts
- test/server/cards/04_JTL/events/EvasiveManeuver.spec.ts
- test/server/cards/04_JTL/units/BunkerDefender.spec.ts
- test/server/cards/04_JTL/units/CloneCombatSquadron.spec.ts
- test/server/cards/04_JTL/units/DilapidatedSkiSpeeder.spec.ts
- test/server/cards/04_JTL/units/IndependentSmuggler.spec.ts
- test/server/cards/04_JTL/units/InsurgentSaboteurs.spec.ts
- test/server/cards/04_JTL/units/SupportingEta2.spec.ts
- test/server/cards/04_JTL/units/VeteranFleetOfficer.spec.ts
> Bunch of cards (set4-bunch9)

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- server/game/core/gameSteps/prompts/SelectCardPrompt.ts
- server/game/gameSystems/SearchDeckSystem.ts
- test/server/cards/02_SHD/events/TripleDarkRaid.spec.ts
- test/server/cards/02_SHD/units/PoeDameronQuickToImprovise.spec.ts
- test/server/cards/03_TWI/events/Reprocess.spec.ts
- test/server/cards/04_JTL/upgrades/TwinLaserTurret.spec.ts
> Improve Choose no target/Take nothing buttons

- server/game/cards/04_JTL/units/TheMandalorianWeatheredPilot.ts
- test/server/cards/04_JTL/units/TheMandalorianWeatheredPilot.spec.ts
> Implementing The Mandalorian, Weathered Pilot

- server/game/cards/04_JTL/units/BB8HappyBeeps.ts
- server/game/cards/04_JTL/units/RetrofittedAirspeeder.ts
- test/server/cards/04_JTL/units/BB8HappyBeeps.spec.ts
- test/server/cards/04_JTL/units/RetrofittedAirspeeder.spec.ts
| BB-8 | Retrofitted Airspeeder |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/46994117-d9e2-412b-892d-5ca637b25782) | ![image](https://github.com/user-attachments/assets/5aaadf60-a893-4688-abc3-27dda12131d3) |
> Add BB-8 and Retrofitted Airspeeder

- server/game/cards/04_JTL/units/NienNunbLoyalCoPilot.ts
- test/server/cards/04_JTL/units/NienNunbLoyalCoPilot.spec.ts
- test/server/core/abilities/keyword/Piloting.spec.ts
Also added a unit test for sneak attack + pilot upgrade card
> JTL Nien Nunb

- server/game/cards/04_JTL/events/PunchIt.ts
- test/server/cards/04_JTL/events/PunchIt.spec.ts
> Implementing Punch It

- server/game/cards/04_JTL/units/KimogilaHeavyFighter.ts
- test/server/cards/04_JTL/units/KimogilaHeavyFighter.spec.ts
[Card](https://swudb.com/card/JTL/222/kimogila-heavy-fighter)
> add kimogila heavy fighter

- server/game/cards/04_JTL/events/CatAndMouse.ts
- server/game/cards/04_JTL/events/HeartlessTactics.ts
- server/game/cards/04_JTL/events/PiercingShot.ts
- server/game/cards/04_JTL/events/TheyHateThatShip.ts
- server/game/cards/04_JTL/units/ATDPOccupier.ts
- server/game/cards/04_JTL/units/AstromechPilot.ts
- server/game/cards/04_JTL/units/DorneanGunship.ts
- server/game/cards/04_JTL/units/SwarmingVultureDroid.ts
- server/game/cards/04_JTL/units/TamRyvoraSearchingForPurpose.ts
- server/game/cards/04_JTL/units/WingGuardSecurityTeam.ts
- server/utils/deck/DeckValidator.ts
- test/server/cards/04_JTL/events/CatAndMouse.spec.ts
- test/server/cards/04_JTL/events/HeartlessTactics.spec.ts
- test/server/cards/04_JTL/events/PiercingShot.spec.ts
- test/server/cards/04_JTL/events/TheyHateThatShip.spec.ts
- test/server/cards/04_JTL/units/ATDPOccupier.spec.ts
- test/server/cards/04_JTL/units/AstromechPilot.spec.ts
- test/server/cards/04_JTL/units/DorneanGunship.spec.ts
- test/server/cards/04_JTL/units/SwarmingVultureDroid.spec.ts
- test/server/cards/04_JTL/units/TamRyvoraSearchingForPurpose.spec.ts
- test/server/cards/04_JTL/units/WingGuardSecurityTeam.spec.ts
> Bunch of cards (set4 bunch11)

- server/game/cards/04_JTL/events/Commandeer.ts
- server/game/cards/04_JTL/events/FlyCasual.ts
- server/game/cards/04_JTL/events/SweepTheArea.ts
- server/game/cards/04_JTL/units/AllegiantGeneralPrydeRuthlessAndLoyal.ts
- server/game/cards/04_JTL/units/BoShekCharismaticSmuggler.ts
- server/game/cards/04_JTL/units/RazorCrestRideForHire.ts
- server/game/cards/04_JTL/units/SeasonedFleetAdmiral.ts
- test/server/cards/04_JTL/events/Commandeer.spec.ts
- test/server/cards/04_JTL/events/FlyCasual.spec.ts
- test/server/cards/04_JTL/events/SweepTheArea.ts
- test/server/cards/04_JTL/units/AllegiantGeneralPrydeRuthlessAndLoyal.spec.ts
- test/server/cards/04_JTL/units/BoShekCharismaticSmuggler.spec.ts
- test/server/cards/04_JTL/units/RazorCrestRideForHire.spec.ts
- test/server/cards/04_JTL/units/SeasonedFleetAdmiral.spec.ts
> Bunch of cards (set4-bunch12)

- server/game/cards/04_JTL/units/FireballAnExplosionWithWings.ts
- test/server/cards/04_JTL/units/FireballAnExplosionWithWings.spec.ts
Shoutout to @Twet1 for getting this one started 🙌
> Fireball, An Explosion with Wings

- server/game/cards/04_JTL/leaders/AdmiralTrenchChkchkchkchk.ts
- server/game/core/card/LeaderUnitCard.ts
- test/server/cards/04_JTL/leaders/AdmiralTrenchChkchkchkchk.spec.ts
| Leader side | Unit side |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/586ba77a-a80b-498e-929b-023fe974599c) | ![image](https://github.com/user-attachments/assets/6f8a6ca7-783b-46dd-9e42-8d3bcce98dd3) |
> Add Admiral Trench leader

- server/game/cards/04_JTL/events/BarrelRoll.ts
- test/server/cards/04_JTL/events/BarrelRoll.spec.ts
[Card](https://swudb.com/card/JTL/228/barrel-roll)
> implement barrel roll

- server/game/cards/03_TWI/leaders/QuinlanVosStickingTheLanding.ts
- server/game/cards/03_TWI/units/R2D2FullofSolutions.ts
- server/game/gameSystems/DrawSpecificCardSystem.ts
- server/utils/deck/DeckValidator.ts
- test/server/cards/03_TWI/leaders/QuinlanVosStickingTheLanding.spec.ts
- R2 was revealing the card when it shouldn't
- Quinlan leader unit side was not optional
- Swarming Vulture Droid deck logic wasn't working
> Fix some reported bugs

- server/game/abilities/keyword/AmbushAbility.ts
- server/game/gameSystems/DeployAndAttachPilotLeaderSystem.ts
- test/server/cards/04_JTL/leaders/BobaFettAnyMethodsNecessary.spec.ts
Updated Boba Fett test cases to pilot a vehicle with Ambush
> Fix an issue with Piloting leaders triggering Ambush on deploy

- server/gamenode/GameServer.ts
- server/gamenode/Lobby.ts
Support for game name field in the create game form. Also shortens id when name is not provided.
> Lobby name support

- server/game/cards/04_JTL/events/Commandeer.ts
- server/game/cards/04_JTL/leaders/landoCalrissianBuyingTime.ts
- server/game/cards/04_JTL/units/RazorCrestRideForHire.ts
- test/server/cards/04_JTL/leaders/AdmiralHoldoWereNotAlone.spec.ts
- test/server/cards/04_JTL/leaders/LandoCalrissianBuyingTime.spec.ts
> Lando Calrissian, Buying Time

- server/game/cards/04_JTL/units/TraceMartezTrustingSister.ts
- test/server/cards/04_JTL/units/TraceMartezTrustingSister.spec.ts
> Implementing Trace Martez, Trusting Sister

- server/game/cards/04_JTL/units/LeiaOrganaPilotsToYourStations.ts
- test/server/cards/04_JTL/units/LeiaOrganaPilotsToYourStations.spec.ts
> we can pass leia ability

- server/game/gameSystems/ChooseModalEffectsSystem.ts
| Poe Dameron | Vigilance | Aggression |
| :---: | :---: | :---: |
| <img width=200 src="https://github.com/user-attachments/assets/1a316144-dc3b-442f-8e3d-ffa8a5b3ee2e" /> | <img width=200 src="https://github.com/user-attachments/assets/0c005153-b375-4b3c-bdfd-e2c595fc1c03" /> | <img width=200 src="https://github.com/user-attachments/assets/8bc717ce-c404-4713-abf8-53bfa3572d49" /> |
> Add modal choices to game chat - fixes #746

- server/game/cards/04_JTL/events/ThereIsNoEscape.ts
- test/server/cards/04_JTL/events/ThereIsNoEscape.spec.ts
> There Is No Escape

- server/game/cards/04_JTL/units/SnapWexleyResistanceReconFlier.ts
- test/server/cards/04_JTL/units/SnapWexleyResistanceReconFlier.spec.ts
> snap wexley

- server/game/cards/04_JTL/events/CoveringTheWing.ts
- server/game/cards/04_JTL/events/FightFireWithFire.ts
- test/server/cards/04_JTL/events/CoveringTheWing.spec.ts
- test/server/cards/04_JTL/events/FightFireWithFire.spec.ts
> Implementing Covering the wing and Fight fire with fire

- server/game/cards/04_JTL/units/HanSoloHasHisMoments.ts
- test/server/cards/04_JTL/units/HanSoloHasHisMoments.spec.ts
[Han Solo unit](https://swudb.com/card/JTL/203)
> Han has his moments

- server/game/cards/04_JTL/units/ResistanceBlueSquadron.ts
- test/server/cards/04_JTL/units/ResistanceBlueSquadron.spec.ts
> Implementing Resistance Blue Squadron

- server/game/actions/PlayUpgradeAction.ts
- server/game/cards/04_JTL/events/Eject.ts
- server/game/cards/04_JTL/units/LukeSkywalkerYouStillWithMe.ts
- server/game/cards/04_JTL/units/PhantomIiModifiedToDock.ts
- server/game/core/Constants.ts
- server/game/core/card/Card.ts
- server/game/core/card/NonLeaderUnitCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/event/EventWindow.ts
- server/game/core/gameSteps/abilityWindow/ReplacementEffectWindow.ts
- server/game/core/ongoingEffect/effectImpl/StatsModifierWrapper.ts
- server/game/core/utils/EnumHelpers.ts
- server/game/core/utils/Helpers.ts
- server/game/gameSystems/AttachUpgradeSystem.ts
- server/game/gameSystems/DetachPilotSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/MoveUnitBetweenArenasSystem.ts
- server/game/gameSystems/ReplacementEffectSystem.ts
- test/server/cards/04_JTL/events/Eject.spec.ts
- test/server/cards/04_JTL/units/LukeSkywalkerYouStillWithMe.spec.ts
- test/server/cards/04_JTL/units/PhantomIiModifiedToDock.spec.ts
Added systems to support detaching pilots
> Add Eject, Luke pilot unit, Phantom II

- server/game/cards/04_JTL/units/HanSoloHasHisMoments.ts
- test/server/cards/04_JTL/units/HanSoloHasHisMoments.spec.ts
Taking this [comment](https://github.com/SWU-Karabast/forceteki/pull/831#discussion_r1986159669) into account
> improve new han solo unit

- server/game/cards/04_JTL/units/BiggsDarklighterTheyllNeverStopUs.ts
- test/server/cards/04_JTL/units/BiggsDarklighterTheyllNeverStopUs.spec.ts
[Card](https://swudb.com/card/JTL/150/biggs-darklighter-they'll-never-stop-us)
> add Biggs Darklighter

- server/game/cards/04_JTL/units/PoeDameronOneHellOfAPilot.ts
- test/server/cards/04_JTL/units/PoeDameronOneHellOfAPilot.spec.ts
[Card](https://swudb.com/card/JTL/100)
> Poe dameron one hell of a pilot

- server/game/cards/04_JTL/units/EchoBaseEngineer.ts
- test/server/cards/04_JTL/units/EchoBaseEngineer.spec.ts
> EchoBaseEngineer

- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- test/server/cards/02_SHD/events/EvidenceOfTheCrime.spec.ts
- test/server/cards/04_JTL/units/ShuttleST149UnderKrennicsAuthority.spec.ts
> Update logic for upgrades changing both controller and arenas

- server/game/cards/04_JTL/events/AllWingsReportIn.ts
- test/server/cards/04_JTL/events/AllWingsReportIn.spec.ts
> Implementing All Wings Report In

- server/game/cards/01_SOR/events/Cunning.ts
- server/game/cards/02_SHD/units/MigsMayfeldTriggerman.ts
- server/game/gameSystems/MoveCardSystem.ts
- test/server/cards/01_SOR/events/Cunning.spec.ts
- test/server/cards/02_SHD/events/TripleDarkRaid.spec.ts
- test/server/cards/02_SHD/units/MigsMayfeldTriggerman.spec.ts
- Fix Triple Dark Raid with Pilot Leaders
- Migs Mayfeld will discard for all cases now (hopefully)
- Cunning can no longer return units with Pilot leaders attached
> Bug Fixes - TDR, Migs, Cunning

- server/game/cards/04_JTL/units/PantoranStarshipThief.ts
- test/server/cards/04_JTL/units/PantoranStarshipThief.spec.ts
> Add Pantoran Starship Thief

- server/game/cards/04_JTL/events/FocusFire.ts
- test/server/cards/04_JTL/events/FocusFire.spec.ts
> Implementing Focus Fire

- server/game/cards/04_JTL/units/WarJuggernaut.ts
- test/server/cards/04_JTL/units/WarJuggernaut.spec.ts
Proposed partial fix for:
https://github.com/SWU-Karabast/forceteki/issues/860
I suspect the FE needs some updates to make it more visible too
> Update War Juggernaut Prompt

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- test/server/cards/02_SHD/leaders/DoctorAphraRapaciousArchaeologist.spec.ts
Small issue was blocking the Corvus PR, this resolves it
> Don't directly call `canAffect()` for effective target

- server/game/cards/04_JTL/units/TheGhostHeartOfTheFamily.ts
- server/game/core/Constants.ts
- server/game/core/card/Card.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/server/cards/04_JTL/units/TheGhostHeartOfTheFamily.spec.ts
> The Ghost, Heart of the Family

- server/game/gameSystems/ViewCardSystem.ts
- test/server/cards/02_SHD/units/BazineNetalSpyForTheFirstOrder.spec.ts
> Bazine no longer discards herself after choosing nothing

- test/server/cards/04_JTL/units/CorvusInfernoSquadronRaider.spec.ts
> add more tests

- server/game/cards/03_TWI/events/ImproprietyAmongThieves.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- test/server/cards/03_TWI/events/ImproprietyAmongThieves.spec.ts
also added isExhausted() function to UnitProperties
> implement ImproprietyAmongThieves

- server/game/cards/04_JTL/events/TimelyReinforcements.ts
- test/server/cards/04_JTL/events/TimelyReinforcements.spec.ts
[Card](https://swudb.com/card/JTL/130)
> add timely reinforcements

- server/game/cards/04_JTL/units/StolenATHauler.ts
- server/game/core/Player.js
- server/game/core/ongoingEffect/effectImpl/PlayFromDiscardProperties.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/server/cards/04_JTL/units/StolenATHauler.spec.ts
> Stolen AT-Hauler

- server/game/cards/04_JTL/events/InTheHeatOfBattle.ts
- test/server/cards/04_JTL/events/InTheHeatOfBattle.spec.ts
> In the Heat of Battle

- server/game/gameSystems/IndirectDamageToPlayerSystem.ts
Updated the indirect damage effect message.  Refactored the code as well
> Issue #909 fix for indirect damage effect message

- server/game/cards/03_TWI/units/AhsokaTanoAlwaysReadyForTrouble.ts
- test/server/cards/03_TWI/units/AhsokaTanoAlwaysReadyForTrouble.spec.ts
> AhsokaTanoSet3

- server/game/abilities/keyword/BountyAbility.ts
- test/server/cards/02_SHD/leaders/BosskHuntingHisPrey.spec.ts
> Fix contract check on Bossk ability to allow defeated leaders

- server/game/cards/04_JTL/units/RaddusHoldosFinalCommand.ts
- server/game/core/Player.js
- test/server/cards/04_JTL/units/RaddusHoldosFinalCommand.spec.ts
> fix leader bug with raddus and add tests

- server/game/cards/03_TWI/units/PadmeAmidalaPursuingPeace.ts
- test/server/cards/03_TWI/units/PadmeAmidalaPursuingPeace.spec.ts
> Implemented Padme Amidala Pursuing Peace

- server/game/cards/04_JTL/units/L337GetOutOfMySeat.ts
- server/game/core/attack/AttackFlow.ts
- server/game/core/card/Card.ts
- server/game/core/card/NonLeaderUnitCard.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/gameSystems/DetachPilotSystem.ts
- server/game/gameSystems/MoveUnitBetweenArenasSystem.ts
- test/server/cards/04_JTL/units/L337GetOutOfMySeat.spec.ts
[Card](https://swudb.com/card/JTL/049)
> l3-37 draft

- server/gamenode/Lobby.ts
- server/logger.ts
Updated the log format to support json objects, and updated the Lobby to use the new format.
here is an example of the logFormatter 'printf' style
and here is the pure json that cloudwatch would receive
> More JSON Logger updates

- server/game/cards/01_SOR/leaders/IdenVersioInfernoSquadCommander.ts
- server/game/cards/02_SHD/leaders/LandoCalrissianWithImpeccableTaste.ts
- server/game/cards/04_JTL/units/HanSoloHasHisMoments.ts
- server/game/stateWatchers/UnitsDefeatedThisPhaseWatcher.ts
- test/server/cards/01_SOR/leaders/IdenVersioInfernoSquadCommander.spec.ts
- test/server/cards/02_SHD/leaders/LandoCalrissianWithImpeccableTaste.spec.ts
- test/server/cards/04_JTL/units/HanSoloHasHisMoments.spec.ts
> Fix Lando and Iden leaders, and Han Solo JTL unit

- server/game/gameSystems/LookMoveDeckCardsTopOrBottomSystem.ts
- server/game/gameSystems/MoveCardSystem.ts
- test/server/cards/01_SOR/units/InfernoFourUnforgetting.spec.ts
- test/server/cards/03_TWI/events/PrivateManufacturing.spec.ts
> Improve Inferno Four and Private Manufacturing chat logs

- test/server/cards/01_SOR/units/DistantPatroller.spec.ts
- test/server/cards/01_SOR/units/GeneralKrellHeartlessTactician.spec.ts
- test/server/cards/01_SOR/units/InfernoFourUnforgetting.spec.ts
- test/server/cards/01_SOR/units/ObiWanKenobiFollowingFate.spec.ts
- test/server/cards/01_SOR/units/YodaOldMaster.spec.ts
First 5 tests updated to utilise No Glory Only results
> First set of When defeated tests

- server/game/abilities/keyword/AmbushAbility.ts
- server/game/actions/InitiateAttackAction.ts
Update Ambush to not ready the unit before the attack.
> Update Ambush to match CR4

- server/game/cards/04_JTL/leaders/HanSoloNeverTellMeTheOdds.ts
- test/server/cards/04_JTL/leaders/HanSoloNeverTellMeTheOdds.spec.ts
> Switch JTL Han Solo leader to use display prompt

- server/game/cards/03_TWI/units/TacticalDroidCommander.ts
- test/server/cards/03_TWI/units/TacticalDroidCommander.spec.ts
> Don't trigger Tactical Droid Commander when played

- server/game/cards/01_SOR/bases/EnergyConversionLab.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/SequentialSystem.ts
- server/game/gameSystems/SimultaneousSystem.ts
- test/server/cards/01_SOR/bases/EnergyConversionLab.spec.ts
Fixing this issue: https://github.com/SWU-Karabast/forceteki/issues/1005
> All targets legal

- server/game/cards/02_SHD/events/GiveInToYourAnger.ts
- server/game/cards/02_SHD/units/LurkingTIEPhantom.ts
- server/game/core/Constants.ts
- server/game/core/GameObject.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/gameSteps/ActionWindow.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/core/ongoingEffect/effectImpl/MustAttackProperties.ts
- server/game/core/utils/Helpers.ts
- server/game/gameSystems/AttackStepsSystem.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
- server/game/gameSystems/PlayerLastingEffectSystem.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/server/cards/02_SHD/events/GiveInToYourAnger.spec.ts
> Add Give In to Your Anger

- server/game/cards/04_JTL/units/AdmiralYularenFleetCoordinator.ts
- server/game/core/gameSystem/LastingEffectPropertiesBase.ts
- server/game/core/utils/Helpers.ts
- server/game/gameSystems/CardLastingEffectSystem.ts
- server/game/gameSystems/LookAtSystem.ts
- server/game/gameSystems/ViewCardSystem.ts
- test/server/cards/04_JTL/units/AdmiralYularen.spec.ts
Now Qira says that it looked at the opponent hand instead of "a card" and Admiral Yularen provides a description for its lasting effect, including the keyword that was chosen.
> Improve Qira and Admiral Yularen chat messages

- server/utils/deck/DeckValidator.ts
> Add Jango, TDR, and DJ to the banned cards list

- server/game/core/event/EventWindow.ts
- server/game/core/gameSteps/abilityWindow/TriggerWindowBase.ts
- test/server/cards/01_SOR/units/BosskDeadlyStalker.spec.ts
> Fix Bossk + NTATOT interaction

- server/game/cards/04_JTL/units/NienNunbLoyalCoPilot.ts
- test/server/cards/04_JTL/units/NienNunbLoyalCoPilot.spec.ts
> Fix Niun Nunb giving a negative stats increase

- server/game/gameSystems/CreateTokenUnitSystem.ts
- test/server/cards/03_TWI/units/ChancellorPalpatineWartimeChancellor.spec.ts
> Fix Chancellor Palpatine unit readying opponent's tokens

- server/game/actions/PlayEventAction.ts
- server/game/core/gameSteps/AbilityResolver.js
- test/server/cards/02_SHD/units/TechSourceOfInsight.spec.ts
> Fix playing events owned by other players

- server/game/cards/01_SOR/units/BosskDeadlyStalker.ts
- server/game/cards/01_SOR/units/ColonelYularenIsbDirector.ts
- server/game/cards/01_SOR/units/FightersForFreedom.ts
- server/game/cards/02_SHD/leaders/BobaFettDaimyo.ts
- server/game/cards/02_SHD/leaders/CadBaneHeWhoNeedsNoIntroduction.ts
- server/game/cards/02_SHD/leaders/HondoOhnakaThatsGoodBusiness.ts
- server/game/cards/02_SHD/leaders/TheMandalorianSwornToTheCreed.ts
- server/game/cards/02_SHD/units/DengarTheDemolisher.ts
- server/game/cards/02_SHD/units/KraytDragon.ts
- server/game/cards/02_SHD/units/LadyProximaWhiteWormMatriarch.ts
- server/game/cards/02_SHD/units/MazKanataPirateQueen.ts
- server/game/cards/02_SHD/units/TobiasBeckettITrustNoOne.ts
- server/game/cards/02_SHD/units/ToroCalicanAmbitiousUpstart.ts
- server/game/cards/03_TWI/leaders/QuinlanVosStickingTheLanding.ts
- server/game/cards/03_TWI/units/FivesInSearchOfTruth.ts
- server/game/cards/03_TWI/units/KiAdiMundiComposedAndConfident.ts
- server/game/cards/03_TWI/units/LuxBonteriRenegadeSeparatist.ts
- server/game/cards/03_TWI/units/MasAmeddaViceChair.ts
- server/game/cards/03_TWI/units/PoggleTheLesserArchdukeOfTheStalgasinHive.ts
- server/game/cards/03_TWI/units/TacticalDroidCommander.ts
- server/game/cards/04_JTL/units/BlackSquadronScoutWing.ts
- server/game/stateWatchers/CardsPlayedThisPhaseWatcher.ts
- test/server/cards/01_SOR/units/ColonelYularenIsbDirector.spec.ts
- test/server/cards/03_TWI/units/KiAdiMundiComposedAndConfident.spec.ts
- test/server/cards/03_TWI/units/LuxBonteriRenegadeSeparatist.spec.ts
- test/server/cards/04_JTL/units/BlackSquadronScoutWing.spec.ts
Fixes #1028 and probably a few other issues we didn't know of.
> Use event.player instead of event.card.controller for onCardPlayed triggers

- server/game/cards/03_TWI/leaders/QuinlanVosStickingTheLanding.ts
- test/server/cards/03_TWI/leaders/QuinlanVosStickingTheLanding.spec.ts
> Fix Quinlan deployed ability with piloting

- server/game/core/gameSystem/AggregateSystem.ts
- server/game/gameSystems/SimultaneousSystem.ts
- test/server/cards/01_SOR/bases/EnergyConversionLab.spec.ts
Followup work that needs to be done:
- ECL should be triggerable when there's no target
- SequentialSystem needs similar changes
> Hotfix to ECL targeting issue

- server/game/core/Player.ts
- server/game/core/card/Card.ts
#resolved issue where undeployed leaders weren't getting saved
> #resolved issue where undeployed leaders weren't getting saved

- server/game/cards/01_SOR/upgrades/Traitorous.ts
- server/game/core/ability/TriggeredAbility.ts
- server/game/gameSystems/AttachUpgradeSystem.ts
- test/server/cards/04_JTL/units/HondoOhnakaSuperfluousSwindler.spec.ts
> Fix resolution of triggered abilities when changing controller

- server/game/gameSystems/IndirectDamageToPlayerSystem.ts
- test/server/cards/04_JTL/units/HuntingAggressor.spec.ts
> Hunting Aggressor shouldn't increase indirect damage dealt to self

- server/game/gameSystems/AttachUpgradeSystem.ts
- test/server/cards/04_JTL/units/L337GetOutOfMySeat.spec.ts
> Fix assertion when trying to attach L3-37 to a unit being defeated

- server/game/cards/03_TWI/events/ExecuteOrder66.ts
- server/game/cards/04_JTL/events/ShootDown.ts
- server/game/cards/04_JTL/units/DarthVaderScourgeOfSquadrons.ts
- server/game/core/ability/AbilityContext.ts
- server/game/core/event/GameEvent.ts
- test/server/cards/02_SHD/units/TarffulKashyyykChieftain.spec.ts
- test/server/cards/03_TWI/events/ExecuteOrder66.spec.ts
- test/server/cards/04_JTL/events/ShootDown.spec.ts
- test/server/cards/04_JTL/units/DarthVaderScourgeOfSquadrons.spec.ts
> Prevent willDefeat triggers if event has been replaced

- server/game/Interfaces.ts
- server/game/cards/03_TWI/upgrades/ForTheRepublic.ts
- server/game/core/ability/KeywordHelpers.ts
- server/game/core/card/Card.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/ongoingEffect/OngoingEffect.ts
- server/game/core/ongoingEffect/OngoingEffectBuilder.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/core/ongoingEffect/effectImpl/DynamicOngoingEffectImpl.ts
- server/game/core/ongoingEffect/effectImpl/GainAbility.ts
- server/game/core/ongoingEffect/effectImpl/GainKeyword.ts
- server/game/core/ongoingEffect/effectImpl/OngoingEffectValueWrapper.ts
- server/game/core/ongoingEffect/effectImpl/StaticOngoingEffectImpl.ts
- server/game/ongoingEffects/OngoingEffectLibrary.ts
- test/server/cards/03_TWI/upgrades/ForTheRepublic.spec.ts
- test/server/cards/04_JTL/units/TheGhostHeartOfTheFamily.spec.ts
> Add For The Republic

- server/game/cards/04_JTL/upgrades/GrimValor.ts
- server/game/core/card/LeaderUnitCard.ts
- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/gameSystems/DeployAndAttachPilotLeaderSystem.ts
- test/server/cards/02_SHD/upgrades/InspiringMentor.spec.ts
- test/server/cards/04_JTL/units/LukeSkywalkerYouStillWithMe.spec.ts
- test/server/cards/04_JTL/units/PantoranStarshipThief.spec.ts
- test/server/core/abilities/keyword/Piloting.spec.ts
- test/server/core/card/Upgrade.spec.ts
> Enforce upgrades attachment condition

- scripts/fetchdata.js
- server/utils/deck/DeckValidator.ts
Confirmed with Luthen:
| Open Format | Premier Format |
| <img width="964" alt="Screenshot 2025-04-30 at 8 17 49 PM" src="https://github.com/user-attachments/assets/e65a9f50-19f7-4a16-954a-e8a78178273b" /> | <img width="894" alt="Screenshot 2025-04-30 at 8 18 06 PM" src="https://github.com/user-attachments/assets/e3bb8c79-7de2-49f3-958f-ccd4be9aaa94" /> |
> Add basic setup for supporting the LOF set

- server/game/cards/05_LOF/events/DrainEssence.ts
- server/game/cards/05_LOF/units/DarthSidiousThePhantomMenace.ts
- server/game/gameSystems/GameSystemLibrary.ts
- test/server/cards/05_LOF/events/DrainEssence.spec.ts
- test/server/cards/05_LOF/units/DarthSidiousThePhantomMenace.spec.ts
> Legends of the Force | Drain Essence & Darth Sidious

- server/game/cards/05_LOF/leaders/QuiGonJinStudentOfTheLivingForce.ts
- test/server/cards/05_LOF/leaders/QuiGonJinStudentOfTheLivingForce.spec.ts
> Adding Quigon Jinn

- server/game/Interfaces.ts
- server/game/core/Constants.ts
- server/game/core/ability/AbilityContext.ts
- server/game/core/ability/KeywordHelpers.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/core/ongoingEffect/OngoingEffectEngine.ts
- server/game/core/ongoingEffect/effectImpl/DynamicOngoingEffectImpl.ts
- server/game/core/ongoingEffect/effectImpl/GainKeyword.ts
- server/game/core/stateWatcher/StateWatcher.ts
- server/game/stateWatchers/LeadersDeployedThisPhaseWatcher.ts
- server/game/stateWatchers/StateWatcherLibrary.ts
- test/server/core/abilities/keyword/Hidden.spec.ts
This is the same as #1135 minus Third Sister because it's not in the database yet and with a new summary property to indicate when hidden is active.
> Add Hidden keyword

- server/game/cards/05_LOF/units/SavageOpressImbuedWithHate.ts
- test/server/cards/05_LOF/units/SavageOpressImbuedWithHate.spec.ts
> savage opress

- server/game/cards/05_LOF/units/ObiwanKenobiProtectivePadawan.ts
- test/server/cards/05_LOF/units/ObiwanKenobiProtectivePadawan.spec.ts
> Add Obi-Wan Kenobi LOF

- server/game/cards/05_LOF/units/MerrinAloneWithTheDead.ts
- server/game/cards/05_LOF/units/PloKoonIDontBelieveInChance.ts
- test/server/cards/05_LOF/units/MerrinAloneWithTheDead.spec.ts
- test/server/cards/05_LOF/units/PloKoonIDontBelieveInChance.spec.ts
| Merrin | Plo Koon |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/d5c25b6c-d330-4eae-b8ae-0a178f5758ff) | ![image](https://github.com/user-attachments/assets/923126ed-7aa5-4936-87e1-4ef0f180b237) |
> Add Merrin and Plo Koon

- server/game/cards/05_LOF/events/AsIHaveForeseen.ts
- test/server/cards/05_LOF/events/AsIHaveForeseen.spec.ts
> Implement As I Have Foreseen

- server/game/cards/05_LOF/units/CaptainEnochCaptainOfTheGuard.ts
- server/game/cards/05_LOF/units/OwenLarsDevotedUncle.ts
- server/game/cards/05_LOF/units/QuiGonJinnTheNegotiationsWillBeShort.ts
- server/game/cards/05_LOF/units/ScytheIntimidatingSilhouette.ts
- test/server/cards/05_LOF/units/CaptainEnochCaptainOfTheGuard.spec.ts
- test/server/cards/05_LOF/units/OwenLarsDevotedUncle.spec.ts
- test/server/cards/05_LOF/units/QuiGonJinnTheNegotiationsWillBeShort.spec.ts
- test/server/cards/05_LOF/units/ScytheIntimidatingSilhouette.spec.ts
> enoch, owen lars, qui gon, scythe

- server/game/cards/05_LOF/units/Terentatek.ts
- test/server/cards/05_LOF/units/Terentatek.spec.ts
> terentatek

- server/game/cards/02_SHD/upgrades/UnrefusableOffer.ts
- server/game/cards/05_LOF/events/CureWounds.ts
- server/game/cards/05_LOF/events/DeathField.ts
- server/game/cards/05_LOF/units/JediConsular.ts
- server/game/cards/05_LOF/upgrades/DarthRevansLightsabers.ts
- test/server/cards/05_LOF/events/CureWounds.spec.ts
- test/server/cards/05_LOF/events/DeathField.spec.ts
- test/server/cards/05_LOF/units/JediConsular.spec.ts
- test/server/cards/05_LOF/upgrades/DarthRevanLightsabers.spec.ts
| Cure Wounds | Death Field |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/1adbd9c6-8e71-478e-b372-42dac7f84f04) | ![image](https://github.com/user-attachments/assets/0089b242-00cb-4503-8055-88085abdbd5f) |
| Jedi Consular | Darth Revan's Lightsabers |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5ad47152-e38a-4dc8-b486-8092220703d0) | ![image](https://github.com/user-attachments/assets/f52e33f1-1b63-41d4-b1fb-786dddf7f0cd) |
> Add Cure Wounds, Death Field, Jedi Consular, Darth Revan's Lightsabers

- server/game/cards/05_LOF/units/HK47ExclamationDieMeatbag.ts
- test/server/cards/05_LOF/units/HK47ExclamationDieMeatbag.spec.ts
> Implement HK-47

- server/gamenode/GameServer.ts
- server/middleware/AuthMiddleWare.ts
- Added a new check that lets us need to retrieve the user only when he first logs in. Afterwards we always check the query whether it already contains the data for the user.
> #Added checks for user logins.

- server/game/cards/05_LOF/upgrades/DarthRevansLightsabers.ts
- test/server/cards/05_LOF/upgrades/DarthRevanLightsabers.spec.ts
The cards says `Sith` and not `Force` 😅
> Fix Darth Revan Lightsabers

- server/game/cards/05_LOF/units/JTypeNubianStarship.ts
- server/game/cards/05_LOF/units/MazKanataTheLightGuides.ts
- server/game/cards/05_LOF/units/PaladinTrainingCorvette.ts
- server/game/core/Constants.ts
- test/server/cards/05_LOF/units/JTypeNubianStarship.spec.ts
- test/server/cards/05_LOF/units/MazKanataTheLightGuides.spec.ts
- test/server/cards/05_LOF/units/PaladinTrainingCorvette.spec.ts
> Maz Kanata, J-Type Nubian Starship, Paladin Training Corvette

- server/game/cards/05_LOF/units/AcolyteOfTheBeyond.ts
- test/server/cards/05_LOF/units/AcolyteOfTheBeyond.spec.ts
> Implementing Acolyte Of The Beyond

- server/game/cards/02_SHD/units/PoeDameronQuickToImprovise.ts
- server/game/core/attack/Attack.ts
- server/game/core/attack/AttackFlow.ts
- server/game/core/card/baseClasses/PlayableOrDeployableCard.ts
- server/game/core/card/propertyMixins/Damage.ts
- server/game/core/card/propertyMixins/LeaderProperties.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- test/server/actions/UnitAttack.spec.ts
- test/server/cards/02_SHD/units/PoeDameronQuickToImprovise.spec.ts
Closes https://github.com/SWU-Karabast/forceteki/issues/1232
Added support for the rule that the attack should skip to completion if the attacker or defender changes control. Also updated the Poe upgrade defeat ability to not be optional when triggered
> Poe1 - Traitorous interaction fix

- server/game/cards/05_LOF/events/LuminousBeings.ts
- server/game/cards/05_LOF/events/ShienFlurry.ts
- server/game/cards/05_LOF/units/YaddleAChanceToMakeThingsRight.ts
- test/server/cards/05_LOF/events/LuminousBeings.spec.ts
- test/server/cards/05_LOF/events/ShienFlurry.spec.ts
- test/server/cards/05_LOF/units/YaddleAChanceToMakeThingsRight.spec.ts
> Yaddle, Luminous Beings and Shien Flurry

- server/gamenode/GameServer.ts
- server/utils/deck/DeckService.ts
Reference to the issue. This shoould fix it.
https://github.com/SWU-Karabast/forceteki-client/issues/321
> Che bato/Each deck is copied multiple times on first sign-in

- server/game/cards/05_LOF/leaders/KitFistoFocusedJediMaster.ts
- test/server/cards/05_LOF/leaders/KitFistoFocusedJediMaster.spec.ts
> Kit Fisto Focused Jedi Master implementation

- server/game/cards/05_LOF/events/ImpossibleEscape.ts
- server/game/cards/05_LOF/events/TheWillOfTheForce.ts
- server/game/core/Constants.ts
- server/game/core/ability/CardAbility.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/MoveCardSystem.ts
- server/game/gameSystems/OptionalSystem.ts
- server/game/gameSystems/UseTheForceSystem.ts
- test/server/cards/05_LOF/events/ImpossibleEscape.spec.ts
- test/server/cards/05_LOF/events/TheWillOfTheForce.spec.ts
| The Will of the Force | Impossible Escape |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/1b6bfcbf-674e-4b2b-8dd5-44b53b3911b0) | ![image](https://github.com/user-attachments/assets/903fc5b6-ad4b-41dc-aac6-161d5e4d7748) |
> Add The Will of the Force and Impossible Escape

- server/game/cards/05_LOF/units/ChirrutImweBlindButNotDeaf.ts
- test/server/cards/05_LOF/units/ChirrutImweBlindButNotDeaf.spec.ts
> Add Chirrut Imwe, Blind but not Deaf

- server/game/core/Game.js
- server/game/core/gameSteps/abilityWindow/TriggeredAbilityWindow.ts
- test/server/cards/02_SHD/units/KraytDragon.spec.ts
> Ignore controller requirement when resolving triggered abilities

- server/game/cards/01_SOR/units/AgentKallusSeekingTheRebels.ts
- server/game/cards/01_SOR/units/GideonHaskRuthlessLoyalist.ts
- server/game/cards/02_SHD/units/ArquitensAssaultCruiser.ts
- server/game/cards/03_TWI/units/CalculatingMagnaGuard.ts
- test/server/cards/01_SOR/units/AgentKallusSeekingTheRebels.spec.ts
- test/server/cards/01_SOR/units/GideonHaskRuthlessLoyalist.spec.ts
- test/server/cards/02_SHD/units/ArquitensAssaultCruiser.spec.ts
- test/server/cards/03_TWI/units/CalculatingMagnaGuard.spec.ts
> Fix a few abilities not using LKI correctly

- server/game/Interfaces.ts
- server/game/core/Player.ts
- test/helpers/DeckBuilder.js
- test/helpers/PlayerInteractionWrapper.js
- test/server/cards/02_SHD/units/DoctorEvazanWantedOnTwelveSystems.spec.ts
- test/server/cards/02_SHD/units/ScanningOfficer.spec.ts
- test/server/cards/02_SHD/upgrades/Wanted.spec.ts
> Add support for resource state to tests and captured game state

- Caddyfile
- Dockerfile
- server/gamenode/GameServer.ts
New Dockerfile for standardard fargate service.
> Prep fargate infra

- test/server/cards/05_LOF/units/KitFistosAetherspriteGoodHunting.spec.ts
I copied & pasted the tests from Power Failure and forgot to actually use the card in them 😅
> Fix Kit Fisto's Aethersprite tests

- server/game/cards/05_LOF/events/Pounce.ts
- server/game/cards/05_LOF/events/ProtectThePod.ts
- server/game/cards/05_LOF/leaders/AhsokaTanoFightingForPeace.ts
- server/game/cards/05_LOF/units/GrapplingGuardian.ts
- test/server/cards/05_LOF/events/Pounce.spec.ts
- test/server/cards/05_LOF/events/ProtectThePod.spec.ts
- test/server/cards/05_LOF/leaders/AhsokaTanoFightingForPeace.spec.ts
- test/server/cards/05_LOF/units/GrapplingGuardian.spec.ts
> Bunch of cards

- server/game/TargetInterfaces.ts
- server/game/cards/02_SHD/events/EndlessLegions.ts
- server/game/cards/02_SHD/leaders/HanSoloWorthTheRisk.ts
- server/game/cards/02_SHD/leaders/LandoCalrissianWithImpeccableTaste.ts
- server/game/core/ability/abilityTargets/CardTargetResolver.ts
- test/server/cards/02_SHD/events/EndlessLegions.spec.ts
- test/server/cards/02_SHD/leaders/HanSoloWorthTheRisk.spec.ts
- test/server/gameSystems/CaptureSystem.spec.ts
> Fix Han Solo 2 deployed ability

- server/game/cards/05_LOF/events/Shatterpoint.ts
- test/server/cards/05_LOF/events/Shatterpoint.spec.ts
> shatterpoint

- server/game/cards/05_LOF/units/BD1BeepBooBooBweep.ts
- server/game/cards/05_LOF/units/LothCat.ts
- server/game/cards/05_LOF/upgrades/BolsteredEndurance.ts
- test/server/cards/05_LOF/units/BD1BeepBooBooBweep.spec.ts
- test/server/cards/05_LOF/units/LothCat.spec.ts
- test/server/cards/05_LOF/upgrades/BolsteredEndurance.spec.ts
> BD-1, Loth-Cat, Bolstered Endurance

- server/game/cards/05_LOF/leaders/BarrissOffeeWeHaveBecomeVillains.ts
- test/server/cards/05_LOF/leaders/BarrissOffeeWeHaveBecomeVillains.spec.ts
> Barriss Offee

- server/game/cards/05_LOF/units/AcclamatorAssaultShip.ts
- server/game/cards/05_LOF/units/BlockadeRunner.ts
- server/game/cards/05_LOF/units/InvasionControlShip.ts
- server/game/cards/05_LOF/units/MedicalFrigate.ts
- test/server/cards/05_LOF/units/AcclamatorAssaultShip.spec.ts
- test/server/cards/05_LOF/units/BlockadeRunner.spec.ts
- test/server/cards/05_LOF/units/InvasionControlShip.spec.ts
- test/server/cards/05_LOF/units/MedicalFrigate.spec.ts
| Acclamator Assault Ship | Blockade Runner |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/55b7b0d3-a942-4ca6-885b-cece893a6b5a) | ![image](https://github.com/user-attachments/assets/af764539-cae5-47fe-8246-71dec3817049) |
| Invasion Control Ship | Medical Frigate |
| --- | --- |
|  ![image](https://github.com/user-attachments/assets/f6bf439b-58b3-4a1d-af6a-b47125b13e6b) | ![image](https://github.com/user-attachments/assets/5949e32b-2fbb-4360-b6a4-b80e7c2b9989) |
> Acclamator Assault Ship, Blockade Runner, Invasion Control Ship, Medical Frigate

- server/game/cards/05_LOF/leaders/AnakinSkywalkerTemptedByTheDarkSide.ts
- server/game/core/Constants.ts
- server/game/core/cardSelector/BaseCardSelector.ts
- server/game/core/utils/EnumHelpers.ts
- server/game/gameSystems/PlayCardSystem.ts
- test/server/cards/05_LOF/leaders/AnakinSkywalkerTemptedByTheDarkSide.spec.ts
> Add LOF Anakin Leader and NonUnit filter/type

- server/game/cards/05_LOF/events/Overpower.ts
- server/game/cards/05_LOF/units/TheSonEmbodimentOfDarkness.ts
- server/game/cards/05_LOF/upgrades/AscensionCable.ts
- server/game/cards/05_LOF/upgrades/YodasLightsaber.ts
- test/server/cards/05_LOF/events/Overpower.spec.ts
- test/server/cards/05_LOF/units/TheSonEmbodimentOfDarkness.spec.ts
- test/server/cards/05_LOF/upgrades/AscensionCable.spec.ts
- test/server/cards/05_LOF/upgrades/YodasLightsaber.spec.ts
> Four LOF Cards

- server/game/cards/05_LOF/units/AdeptOfAnger.ts
- server/game/cards/05_LOF/units/HeavyMissileGunship.ts
- server/game/cards/05_LOF/units/LifeWindSage.ts
- server/game/cards/05_LOF/units/PraetorianGuard.ts
- server/game/cards/05_LOF/units/RaveningGundark.ts
- test/server/cards/05_LOF/units/AdeptOfAnger.spec.ts
- test/server/cards/05_LOF/units/HeavyMissileGunship.spec.ts
- test/server/cards/05_LOF/units/LifeWindSage.spec.ts
- test/server/cards/05_LOF/units/PraetorianGuard.spec.ts
- test/server/cards/05_LOF/units/RaveningGundark.spec.ts
> Praetorian Guard, Heavy Missile Gunship, Adept of Anger, Life Wind Sage, Ravening Gundark

- server/game/cards/05_LOF/events/ForceSlow.ts
- server/game/cards/05_LOF/events/GoIntoHiding.ts
- server/game/cards/05_LOF/events/TrustYourInstincts.ts
- test/server/cards/05_LOF/events/ForceSlow.spec.ts
- test/server/cards/05_LOF/events/GoIntoHiding.spec.ts
- test/server/cards/05_LOF/events/TrustYourInstincts.spec.ts
> Trust Your Instincts, Force Slow, Go Into Hiding

- server/game/actions/PlayUpgradeAction.ts
- server/game/cards/05_LOF/leaders/KyloRenWereNotDoneYet.ts
- server/game/core/ability/PlayCardAction.ts
- server/game/gameSystems/GameSystemLibrary.ts
- server/game/gameSystems/PlayCardSystem.ts
- test/server/cards/04_JTL/units/TheMandalorianWeatheredPilot.spec.ts
- test/server/cards/05_LOF/leaders/KyloRenWereNotDoneYet.spec.ts
| Leader Side | Unit Side |
| ![image](https://github.com/user-attachments/assets/d2e45cb5-9a30-4332-b580-3dbee965ece8) | ![image](https://github.com/user-attachments/assets/80ddcb79-a821-41f2-b701-003c0f2c742a) |
> Kylo Ren, We're Not Done Yet

- server/game/cards/05_LOF/units/CinDralligEsteemedBlademaster.ts
- test/server/cards/05_LOF/units/CinDralligEsteemedBlademaster.spec.ts
> Cin Drallig, Esteemed Blademaster

- server/game/cards/05_LOF/upgrades/BattleFury.ts
- server/game/cards/05_LOF/upgrades/CravingPower.ts
- server/game/cards/05_LOF/upgrades/HeavyBlasterCannon.ts
- test/server/cards/05_LOF/upgrades/BattleFury.spec.ts
- test/server/cards/05_LOF/upgrades/CravingPower.spec.ts
- test/server/cards/05_LOF/upgrades/HeavyBlasterCannon.spec.ts
| Craving Power | Battle Fury | Heavy Blaster Cannon |
| :---: | :---: | :---: |
| ![image](https://github.com/user-attachments/assets/5e2ef671-3f9d-4d2d-98f3-3c68cc0c0037) | ![image](https://github.com/user-attachments/assets/87ead2f1-51c9-47a5-9cc5-677798003702) | ![image](https://github.com/user-attachments/assets/f91ba58c-634d-4e7f-aa31-935d53bb1220) |
> Craving Power, Battle Fury, and Heavy Blaster Cannon

- server/game/cards/05_LOF/upgrades/AscensionCable.ts
- server/game/cards/05_LOF/upgrades/BolsteredEndurance.ts
- server/game/cards/05_LOF/upgrades/ConstructedLightsaber.ts
- server/game/cards/05_LOF/upgrades/CorruptedSaber.ts
- server/game/cards/05_LOF/upgrades/KyloRensLightsaber.ts
- server/game/cards/05_LOF/upgrades/QuiGonJinnsLightsaber.ts
- server/game/cards/05_LOF/upgrades/YodasLightsaber.ts
- test/server/cards/05_LOF/upgrades/ConstructedLightsaber.spec.ts
- test/server/cards/05_LOF/upgrades/CorruptedSaber.spec.ts
- test/server/cards/05_LOF/upgrades/KyloRensLightsaber.spec.ts
| Kylo Ren's Lightsaber | Corrupted Saber |
| ![image](https://github.com/user-attachments/assets/cedf1284-2e16-4dcf-86d5-37cf548f2d59) | ![image](https://github.com/user-attachments/assets/fe0be5b6-3985-4945-93b0-e3fd317185ae) |
> Kylo Ren's Lightsaber & Corrupted Saber

- server/game/Interfaces.ts
- server/game/cards/05_LOF/units/OppoRancisisAncientCouncilor.ts
- test/server/cards/05_LOF/units/OppoRancisisAncientCouncilor.spec.ts
> Oppo Rancisis, Ancient Councilor

- server/game/cards/05_LOF/events/WhirlwindOfPower.ts
- server/game/cards/05_LOF/units/AxeWovesAccomplishedWarrior.ts
- server/game/cards/05_LOF/upgrades/JediHolocron.ts
- test/server/cards/05_LOF/events/WhirlwindOfPower.spec.ts
- test/server/cards/05_LOF/events/WhirlwindOfPower.ts
- test/server/cards/05_LOF/units/AxeWovesAccomplishedWarrior.spec.ts
- test/server/cards/05_LOF/upgrades/JediHolocron.spec.ts
Axe Woves: 
Jedi Holocron:
Whirlwind of power:
> Axe Woves, Jedi holocron and Whirlwind of power

- server/game/cards/05_LOF/leaders/ReyNobody.ts
- test/server/cards/05_LOF/leaders/ReyNobody.spec.ts
> Implementing Rey Nobody

- server/game/cards/05_LOF/events/ConsumedByTheDarkSide.ts
- server/game/cards/05_LOF/events/LastWords.ts
- test/server/cards/05_LOF/events/ConsumedByTheDarkSide.spec.ts
- test/server/cards/05_LOF/events/LastWords.spec.ts
> Implementing Consumed by the dark side, last words

- server/game/cards/05_LOF/events/FollowingThePath.ts
- server/game/cards/05_LOF/events/TheBurdenOfMasters.ts
- server/game/cards/05_LOF/units/TuskenTracker.ts
- test/server/cards/05_LOF/events/FollowingThePath.spec.ts
- test/server/cards/05_LOF/events/TheBurdenOfMasters.spec.ts
- test/server/cards/05_LOF/units/TuskenTracker.spec.ts
> Following the Path, The Burden of Masters, Tusken Tracker

- server/game/cards/05_LOF/events/AlwaysTwo.ts
- test/server/cards/05_LOF/events/AlwaysTwo.spec.ts
> Always Two

- server/game/cards/05_LOF/events/ForceSpeed.ts
- server/game/cards/05_LOF/events/PremonitionOfDoom.ts
- test/server/cards/05_LOF/events/ForceSpeed.spec.ts
- test/server/cards/05_LOF/events/PremonitionOfDoom.spec.ts
| Premonition of Doom | Force Speed |
| ![image](https://github.com/user-attachments/assets/2242372f-547e-41d5-956e-4ff1f69e296e) | ![image](https://github.com/user-attachments/assets/213f393b-7cc0-4fda-99f0-0a75a372a959) |
> Premonition of Doom & Force Speed

- server/game/cards/05_LOF/events/APrecariousPredicament.ts
- server/game/cards/05_LOF/events/TimeOfCrisis.ts
- test/server/cards/05_LOF/events/APrecariousPredicament.spec.ts
- test/server/cards/05_LOF/events/TimeOfCrisis.spec.ts
| A Precarious Predicament | Time of Crisis |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/d94045ef-7cb5-43a9-8396-3956889ed281) | ![image](https://github.com/user-attachments/assets/27d60790-7a1b-47b6-b780-22a8d0089801) |
> Add A Precarious Predicament and Time of Crisis

- server/game/cards/03_TWI/units/ChancellorPalpatineWartimeChancellor.ts
- server/game/cards/05_LOF/events/DisturbanceInTheForce.ts
- test/server/cards/03_TWI/units/ChancellorPalpatineWartimeChancellor.spec.ts
> TWI Palpatine unit: create token if leader unit left play this phase

- server/game/cards/05_LOF/units/BabuFrikHeyyy.ts
- server/game/core/attack/Attack.ts
- server/game/core/attack/AttackFlow.ts
- server/game/gameSystems/AttackStepsSystem.ts
- test/server/cards/05_LOF/units/BabuFrikHeyyy.spec.ts
| ⟡ Babu Frik, Heyyy! |
| :---: |
| ![image](https://github.com/user-attachments/assets/8bb5f94f-a7ff-4d95-a70f-87afad697584) |
> ⟡ Babu Frik, Heyyy!

- server/game/cards/01_SOR/leaders/BobaFettCollectingTheBounty.ts
- server/game/cards/03_TWI/units/ChancellorPalpatineWartimeChancellor.ts
- server/game/cards/05_LOF/events/DisturbanceInTheForce.ts
- test/server/cards/01_SOR/leaders/BobaFettCollectingTheBounty.spec.ts
- test/server/cards/05_LOF/events/DisturbanceInTheForce.spec.ts
> Improve cardLeftPlayWatcher

- server/game/cards/05_LOF/units/DeceptiveShade.ts
- server/game/core/event/EventWindow.ts
- test/server/cards/05_LOF/units/DeceptiveShade.spec.ts
| Deceptive Shade |
| :---: |
| ![image](https://github.com/user-attachments/assets/7885e0da-7631-4a6c-9191-1fbda914071d) |
> Deceptive Shade

- server/gamenode/GameServer.ts
- server/middleware/AuthMiddleWare.ts
- server/utils/user/UserFactory.ts
- Added additional layer of security for tokens:
1. We now check if the token is correct
2. We create the user based off of the ID in the token rather then in the payload
3. If it fails we create an Anon user.
FE PR:
https://github.com/SWU-Karabast/forceteki-client/pull/376
> Security Improvement

- server/game/gameSystems/ResourceCardSystem.ts
- test/server/cards/02_SHD/units/TechSourceOfInsight.spec.ts
> Fix Tech's Smuggle interaction with Resupply

- server/game/cards/04_JTL/units/AnnihilatorTaggesFlagship.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/gameSystems/DefeatCardSystem.ts
- test/server/cards/04_JTL/units/AnnihilatorTaggesFlagship.spec.ts
Add the card title to LKI and use it for Annihilator effect. It'll be relevant for Clone.
> Use LKI for Annihilator effect

- server/game/core/card/baseClasses/InPlayCard.ts
- server/game/core/card/propertyMixins/UnitProperties.ts
- server/game/gameSystems/DefeatCardSystem.ts
- server/game/gameSystems/FrameworkDefeatCardSystem.ts
- test/scenarios/DefeatAttribution.spec.ts
- test/server/cards/01_SOR/events/OverwhelmingBarrage.spec.ts
- test/server/cards/03_TWI/units/DarthMaulRevengeAtLast.spec.ts
- test/server/cards/04_JTL/events/PlanetaryBombardment.spec.ts
- test/server/cards/05_LOF/units/TheLegacyRunDoomedDebris.spec.ts
- test/server/core/card/UniqueRule.spec.ts
- test/server/core/gameSteps/regroupWindow/RegroupPhase.spec.ts
> Add chat log when a unit is defeated

- server/utils/profanityFilter/ProfanityFilter.ts
- server/utils/profanityFilter/termLists/BasicProfanityList.ts
Added some better logic for checking simple ways to try and get around the profanity filter, plus a couple new tokens to reject
> Improve username profanity filtering

- server/game/cards/02_SHD/leaders/HunterOutcastSergeant.ts
- test/server/cards/02_SHD/leaders/HunterOutcastSergeant.spec.ts
> [Bugfix] Reveal resource as part of Hunter's leader ability

- server/gamenode/GameServer.ts
- server/services/DynamoDBInterfaces.ts
- server/utils/user/User.ts
- server/utils/user/UserFactory.ts
Added Backend logic that supports the FE username change force update
FE PR: https://github.com/SWU-Karabast/forceteki-client/pull/390
> # Added field for forcing a user to change their username.

- server/gamenode/Lobby.ts
| Quick Rematch | Regular Rematch |
| <img width="255" alt="Screenshot 2025-06-21 at 4 13 50 PM" src="https://github.com/user-attachments/assets/a8b8bc1c-245a-423d-a1b5-54536c386426" /> | <img width="255" alt="Screenshot 2025-06-21 at 4 15 01 PM" src="https://github.com/user-attachments/assets/647ad6e6-d6cb-4052-8684-f222eb8aa7f1" /> |
> Add a chat notification when a player requests a rematch

- server/game/cards/03_TWI/units/Clone.ts
- server/game/cards/Index.ts
- server/game/core/card/Card.ts
- server/utils/deck/DeckValidator.ts
The `overrideNotImplemented` property wasn't working right in the lobby or Unimplemented page, did a fix for it
> Better support for overrideNotImplemented in main site

- server/game/core/ability/abilityTargets/CardTargetResolver.ts
Confirmed Single is used unless Maul is attacking w/ multiple targets
> SelectCardMode fix

- server/game/abilities/keyword/SaboteurDefeatShieldsAbility.ts
- test/server/cards/01_SOR/units/JedhaAgitator.spec.ts
- test/server/cards/01_SOR/units/WolffeSuspiciousVeteran.spec.ts
- test/server/cards/02_SHD/units/ValiantAssaultShip.spec.ts
- test/server/cards/03_TWI/units/Clone.spec.ts
- test/server/cards/03_TWI/units/EnfysNestChampionOfJustice.spec.ts
- test/server/cards/03_TWI/units/KitFistoTheSmilingJedi.spec.ts
- test/server/cards/04_JTL/units/InsurgentSaboteurs.spec.ts
- test/server/cards/04_JTL/units/TheGhostHeartOfTheFamily.spec.ts
- test/server/core/abilities/keyword/Saboteur.spec.ts
> Fix saboteur requiring to select a target

- server/game/core/ongoingEffect/OngoingEffectEngine.ts
This fixes a couple of failures in the undo tests.
> Resolve effects after undo

- server/gamenode/Lobby.ts
> # Commented out swustats.

- server/game/core/snapshot/SnapshotManager.ts
> Turn prod snapshots back up

- server/game/cards/06_SEC/leaders/SlyMooreCipherInTheDark.ts
- server/game/cards/06_SEC/units/ChancellorPalpatineIAmTheSenate.ts
- server/game/cards/06_SEC/units/SlyMooreWitnessToPower.ts
- test/server/cards/06_SEC/leaders/SlyMooreCipherInTheDark.spec.ts
- test/server/cards/06_SEC/units/ChancellorPalpatineIAmTheSenate.spec.ts
- test/server/cards/06_SEC/units/SlyMooreWitnessToPower.spec.ts
> sly moore, sly moore and chancellor palpatine

- server/game/cards/06_SEC/events/NoOneEverKnew.ts
- server/game/cards/06_SEC/units/B2EMOThatsTwoLies.ts
- server/game/cards/06_SEC/units/PreMorPersonnelCarrier.ts
- test/server/cards/06_SEC/events/NoOneEverKnew.spec.ts
- test/server/cards/06_SEC/units/B2EMOThatsTwoLies.spec.ts
- test/server/cards/06_SEC/units/PreMorPersonnelCarrier.spec.ts
> no one ever knew, b2emo, premor

- server/game/cards/06_SEC/events/BogDownInProcedure.ts
- server/game/cards/06_SEC/events/GrassrootsResistance.ts
- server/game/cards/06_SEC/events/WithThunderousApplause.ts
- server/game/cards/06_SEC/units/KaydelConnixForOurSurvival.ts
- server/game/cards/06_SEC/units/SyrilKarnWhereIsHe.ts
- server/game/cards/06_SEC/units/ViceAdmiralRampartOnSchedule.ts
- test/server/cards/06_SEC/events/BogDownInProcedure.spec.ts
- test/server/cards/06_SEC/events/GrassrootsResistance.spec.ts
- test/server/cards/06_SEC/events/WithThunderousApplause.spec.ts
- test/server/cards/06_SEC/units/KaydelConnixForOurSurvival.spec.ts
- test/server/cards/06_SEC/units/SyrilKarnWhereIsHe.spec.ts
- test/server/cards/06_SEC/units/ViceAdmiralRampartOnSchedule.spec.ts
> grassroots resistance, kaydel connix, vice admiral rampart, with thunderous applause, syril karn, bog down in procedure

- server/game/gameSystems/UseWhenDefeatedSystem.ts
- test/server/cards/04_JTL/units/ChimaeraReinforcingTheCenter.spec.ts
> Fix Chimaera interaction with uniqueness rule

- server/game/cards/01_SOR/events/ForceLightning.ts
- server/game/cards/01_SOR/leaders/HanSoloAudaciousSmuggler.ts
- server/game/cards/02_SHD/events/FinalShowdown.ts
- server/game/cards/02_SHD/units/ZoriiBlissValiantSmuggler.ts
- server/game/cards/04_JTL/events/ThereIsNoEscape.ts
- server/game/cards/04_JTL/units/LukeSkywalkerYouStillWithMe.ts
- server/game/cards/05_LOF/events/MindTrick.ts
- server/game/cards/05_LOF/events/PremonitionOfDoom.ts
- server/game/cards/05_LOF/units/QuiGonJinnsAetherspriteGuidedByTheForce.ts
- server/game/core/gameSystem/GameSystem.ts
- server/game/gameSystems/CaptureSystem.ts
- server/game/gameSystems/CreateForceTokenSystem.ts
- server/game/gameSystems/DelayedEffectSystem.ts
- server/game/gameSystems/DeployAndAttachPilotLeaderSystem.ts
- server/game/gameSystems/DetachPilotSystem.ts
- server/game/gameSystems/LoseGameSystem.ts
- server/game/gameSystems/SelectCardSystem.ts
- server/game/gameSystems/TakeControlOfUnitSystem.ts
- server/game/gameSystems/UseTheForceSystem.ts
- test/server/cards/01_SOR/events/Vigilance.spec.ts
- test/server/cards/01_SOR/leaders/HanSoloAudaciousSmuggler.spec.ts
- test/server/cards/01_SOR/units/RedemptionMedicalFrigate.spec.ts
- test/server/cards/01_SOR/units/WolffeSuspiciousVeteran.spec.ts
- test/server/cards/02_SHD/units/TheClientDictatedByDiscretion.spec.ts
- test/server/cards/03_TWI/leaders/ChancellorPalpatinePlayingBothSides.spec.ts
- test/server/cards/03_TWI/units/JarJarBinksFoolishGungan.spec.ts
- test/server/cards/04_JTL/events/PlanetaryBombardment.spec.ts
- test/server/cards/04_JTL/units/CR90ReliefRunner.spec.ts
> Minor chat improvements

- server/game/cards/06_SEC/units/WarriorOfClanOrdo.ts
- test/server/cards/06_SEC/units/WarriorOfClanOrdo.spec.ts
> warrior of clan ordo

- server/game/cards/06_SEC/units/LibertineUnderNewOwnership.ts
- test/server/cards/06_SEC/units/LibertineUnderNewOwnership.spec.ts
> ⟡ Libertine, Under New Ownership

- server/game/cards/06_SEC/events/RestoreFreedom.ts
- server/game/cards/06_SEC/units/CintaKazTheStruggleComesFirst.ts
- server/game/cards/06_SEC/units/OrnFreeTaaPoliticalPowerBroker.ts
- test/server/cards/06_SEC/events/RestoreFreedom.spec.ts
- test/server/cards/06_SEC/units/CintaKazTheStruggleComesFirst.spec.ts
- test/server/cards/06_SEC/units/OrnFreeTaaPoliticalPowerBroker.spec.ts
> restore freedom, cinta kaz and orn free taa

- server/game/cards/06_SEC/events/TradeRouteTaxation.ts
- test/server/cards/06_SEC/events/TradeRouteTaxation.spec.ts
> Trade Route Taxation

- server/game/cards/06_SEC/units/GeneralGrievousScuttlingToSafety.ts
- server/game/cards/06_SEC/upgrades/DiplomaticImmunity.ts
- test/server/cards/06_SEC/units/GeneralGrievousScuttlingToSafety.spec.ts
- test/server/cards/06_SEC/upgrades/DiplomaticImmunity.spec.ts
> Diplomatic Immunity, General Grievous
